import type { Copy } from './copy.en'

/* Français. Textes d'interface uniquement ; le contenu des pages est dans sections.fr.ts. */
export const fr: Copy = {
  nav: { skip: 'Aller au contenu', home: 'Not by Accident, accueil', main: 'Menu principal', menu: 'Menu', close: 'Fermer', soon: 'Bientôt', breadcrumb: "Fil d'Ariane", homeCrumb: 'Accueil', contact: 'Contact', footer: 'Plan du site' },
  pages: { work: 'Travaux', caseStudies: 'Études de cas', capabilities: 'Expertises', notes: 'Notes', studio: 'Studio', trainings: 'Formations', reports: 'Rapports', contact: 'Contact', search: 'Recherche', privacy: 'Confidentialité', cookies: 'Cookies' },
  index: { write: 'Nous écrire', elsewhere: 'Ailleurs', languages: 'Langue' },
  clock: {
    open: (time: string) => `Ouvert · ${time} Amsterdam`,
    closed: (time: string, back: string) => `Fermé · ${time} Amsterdam · retour ${back}`,
    today: "aujourd'hui",
    tomorrow: 'demain',
  },
  home: { scroll: 'Défiler', viewCase: "Voir l'étude", inProgress: 'En cours', nextVoice: 'Suivant', prevVoice: 'Témoignage précédent', nextVoiceLabel: 'Témoignage suivant', voices: 'Témoignages', of: (a: number, b: number) => `${a} / ${b}` },
  footer: { newBusiness: 'Nouveaux projets', general: 'Général', press: 'Presse', elsewhere: 'Ailleurs', rights: (y: number) => `© ${y} Not by Accident` },
  climate: {
    label: 'Carbone, cette page',
    measuring: 'Mesure de cette page…',
    unit: 'g CO₂e',
    perView: 'par page vue',
    scale: 'Note Sustainable Web Design, de A+ (la plus basse) à F',
    how: 'Notre méthode',
    method:
      'Votre navigateur signale en direct chaque octet transféré par cette page, et nous convertissons le total avec le modèle Sustainable Web Design (v4) via CO2.js, la bibliothèque open source de la Green Web Foundation. Le calcul suppose un réseau électrique de moyenne mondiale et un hébergement standard.',
    why: 'Faible par conception : pages pré-rendues, deux polices auto-hébergées, aucun script de suivi tiers, ni WebGL ni bibliothèque d’animation.',
    unmeasured: (n: number) => `${n} ${n === 1 ? 'fichier' : 'fichiers'} d’autres serveurs n’${n === 1 ? 'a' : 'ont'} pas indiqué de taille et ${n === 1 ? 'n’est' : 'ne sont'} pas compté${n === 1 ? '' : 's'}.`,
  },
  forms: {
    email: 'Adresse e-mail',
    emailHelp: 'Nous ne nous en servons que pour répondre.',
    emailPlaceholder: 'vous@entreprise.fr',
    subscribe: "S'inscrire",
    subscribed: 'Vous êtes sur la liste. Merci.',
    sending: 'Envoi…',
    error: "L'envoi a échoué. Réessayez, ou écrivez-nous directement.",
    offline: "Le formulaire n'est pas encore connecté. Écrivez-nous directement.",
    required: 'Obligatoire',
  },
  work: { viewIndex: 'Index', viewSheet: 'Planche', viewLabel: 'Affichage', cols: { no: 'N°', project: 'Projet', brief: 'Brief', discipline: 'Discipline', place: 'Lieu', year: 'Année' } },
  caseStudies: { read: "Lire l'étude" },
  caseStudy: {
    titleSuffix: 'Étude de cas',
    client: 'Client',
    discipline: 'Discipline',
    location: 'Lieu',
    year: 'Année',
    problem: 'Le problème',
    insight: "L'intuition",
    intervention: 'Ce que nous avons décidé',
    outcome: "Ce qui s'est passé",
    capabilities: 'Expertises',
    gallery: 'Le travail',
    credits: 'Crédits',
    visit: 'Voir le projet',
    next: 'Étude suivante',
    inProgress: 'En cours. La suite dès que possible.',
  },
  capabilities: { group: 'Pratique', count: (n: number) => `${n} ${n === 1 ? 'discipline' : 'disciplines'}` },
  capability: {
    question: 'La question à laquelle elle répond',
    outcome: 'Ce que vous en retirez',
    includes: 'Ce que comprend la mission',
    seen: 'Visible dans le travail',
    alsoIn: (group: string) => `Également dans ${group}`,
    talk: (name: string) => `Parlons de ${name.toLowerCase()}`,
    whatIs: (name: string) => `Qu'est-ce que ${name.toLowerCase()} ?`,
    whatDelivers: (name: string) => `Qu'apporte ${name.toLowerCase()} ?`,
    included: (name: string) => `${name} : ce qui est inclus`,
    all: 'Toutes les expertises',
  },
  notes: { all: 'Tout', filter: 'Filtrer par type', read: 'de lecture', schemaName: 'Le Journal · Not by Accident' },
  note: { next: 'Note suivante', published: 'Publié le', video: 'Vidéo intégrée' },
  trainings: { thanks: 'Vous êtes sur la liste. Nous écrirons dès que les dates seront fixées.' },
  reports: { thanks: 'Merci. Nous écrirons dès que le premier rapport sera en ligne.', meanwhile: 'En attendant, lisez les notes' },
  contact: {
    direct: 'Directement',
    hours: 'Horaires',
    name: 'Nom',
    nameHelp: 'Pour savoir à qui nous écrivons.',
    company: 'Entreprise',
    companyHelp: 'Facultatif.',
    email: 'E-mail',
    emailHelp: 'Nous répondons ici, nulle part ailleurs.',
    budget: 'Budget approximatif',
    budgetHelp: 'Une fourchette suffit. « Pas encore sûr » est une bonne réponse.',
    budgetPick: 'Choisir une fourchette',
    budgetOptions: ['Moins de 25 000 £', '25 000–75 000 £', '75 000–150 000 £', '150 000–300 000 £', 'Plus de 300 000 £', 'Pas encore sûr'],
    message: 'Sur quoi travaillez-vous ?',
    messageHelp: "L'entreprise, et ce que vous voulez changer. Précis vaut mieux que long.",
    send: 'Envoyer',
    thanks: 'Merci. Une personne vous répondra sous un jour ouvré.',
  },
  search: {
    seoTitle: 'Recherche',
    seoDescription: 'Rechercher sur Not by Accident : travaux, expertises et notes.',
    h1: 'Recherche',
    label: 'Rechercher sur le site',
    placeholder: 'Un projet, une note, une discipline…',
    idle: 'Tapez pour chercher dans les études de cas, les notes et les expertises.',
    results: (n: number, q: string) => `${n} ${n === 1 ? 'résultat' : 'résultats'} pour « ${q} »`,
    empty: 'Rien ne correspond pour l’instant. Essayez un mot plus large, ou partez de',
    kinds: { page: 'Page', capability: 'Expertise', case: 'Étude de cas', note: 'Note' },
  },
  privacy: { updated: 'Dernière mise à jour', onThisPage: 'Sur cette page', questions: 'Des questions à ce sujet ? Écrivez à' },
  cookies: { category: 'Catégorie', does: 'Ce qu’il fait', lifespan: 'Durée', fuller: 'Pour une vue complète de ce que nous conservons et pourquoi, voir la', privacyLink: 'notice de confidentialité' },
  notFound: { tidy: 'Remettre en ordre', untidy: 'Annuler', home: "Retour à l'accueil", work: 'Voir les travaux', hint: 'Déplacez les lettres, ou remettez-les dans l’ordre.' },
}
