import type { Copy } from './copy.en'

/* Nederlands. Alleen interfaceteksten; pagina-inhoud staat in sections.nl.ts. */
export const nl: Copy = {
  nav: { skip: 'Naar de inhoud', home: 'Not by Accident, home', main: 'Hoofdmenu', menu: 'Menu', close: 'Sluiten', soon: 'Binnenkort', breadcrumb: 'Kruimelpad', homeCrumb: 'Home', contact: 'Contact', footer: 'Sitemap' },
  pages: { work: 'Werk', caseStudies: 'Cases', capabilities: 'Expertises', notes: 'Notities', studio: 'Studio', trainings: 'Trainingen', reports: 'Rapporten', contact: 'Contact', search: 'Zoeken', privacy: 'Privacy', cookies: 'Cookies' },
  index: { write: 'Schrijf ons', elsewhere: 'Elders', languages: 'Taal' },
  clock: {
    open: (time: string) => `Open · ${time} Amsterdam`,
    closed: (time: string, back: string) => `Gesloten · ${time} Amsterdam · weer open ${back}`,
    today: 'vandaag',
    tomorrow: 'morgen',
  },
  home: { scroll: 'Scroll', viewCase: 'Bekijk de case', inProgress: 'Loopt nog', nextVoice: 'Volgende', prevVoice: 'Vorige reactie', nextVoiceLabel: 'Volgende reactie', voices: 'Reacties van klanten', of: (a: number, b: number) => `${a} / ${b}` },
  footer: { newBusiness: 'Nieuwe opdrachten', general: 'Algemeen', press: 'Pers', elsewhere: 'Elders', rights: (y: number) => `© ${y} Not by Accident` },
  climate: {
    label: 'CO₂, deze pagina',
    measuring: 'Deze pagina wordt gemeten…',
    unit: 'g CO₂e',
    perView: 'per paginaweergave',
    scale: 'Sustainable Web Design-score, A+ (laagst) tot F',
    how: 'Hoe we meten',
    method:
      'Je browser meldt live elke byte die deze pagina overdraagt, en we rekenen het totaal om met het Sustainable Web Design-model (v4) via CO2.js, de opensourcebibliotheek van de Green Web Foundation. Het gaat uit van een wereldwijd gemiddeld stroomnet en standaard hosting.',
    why: 'Laag door ontwerp: vooraf gerenderde pagina’s, twee zelf gehoste lettertypen, geen trackingscripts van derden, geen WebGL en geen animatiebibliotheken.',
    unmeasured: (n: number) => `${n} ${n === 1 ? 'bestand' : 'bestanden'} van andere servers meldde${n === 1 ? '' : 'n'} geen grootte en ${n === 1 ? 'telt' : 'tellen'} niet mee.`,
  },
  forms: {
    email: 'E-mailadres',
    emailHelp: 'We gebruiken het alleen om te antwoorden.',
    emailPlaceholder: 'jij@bedrijf.nl',
    subscribe: 'Aanmelden',
    subscribed: 'Je staat op de lijst. Dank je.',
    sending: 'Versturen…',
    error: 'Dat is niet verstuurd. Probeer het opnieuw, of mail ons direct.',
    offline: 'Het formulier is nog niet gekoppeld. Mail ons direct.',
    required: 'Verplicht',
  },
  work: { viewIndex: 'Index', viewSheet: 'Vel', viewLabel: 'Weergave', cols: { no: 'Nr.', project: 'Project', brief: 'Opdracht', discipline: 'Discipline', place: 'Plaats', year: 'Jaar' } },
  caseStudies: { read: 'Lees de case' },
  caseStudy: {
    titleSuffix: 'Case',
    client: 'Klant',
    discipline: 'Discipline',
    location: 'Locatie',
    year: 'Jaar',
    problem: 'Het probleem',
    insight: 'Het inzicht',
    intervention: 'Wat we besloten',
    outcome: 'Wat er gebeurde',
    capabilities: 'Expertises',
    gallery: 'Het werk',
    credits: 'Credits',
    visit: 'Bekijk het project',
    next: 'Volgende case',
    inProgress: 'Loopt nog. Meer zodra het kan.',
  },
  capabilities: { group: 'Praktijk', count: (n: number) => `${n} ${n === 1 ? 'discipline' : 'disciplines'}` },
  capability: {
    question: 'De vraag die het beantwoordt',
    outcome: 'Waar je mee vertrekt',
    includes: 'Wat de opdracht omvat',
    seen: 'Te zien in het werk',
    alsoIn: (group: string) => `Ook in ${group}`,
    talk: (name: string) => `Praat met ons over ${name.toLowerCase()}`,
    whatIs: (name: string) => `Wat is ${name.toLowerCase()}?`,
    whatDelivers: (name: string) => `Wat levert ${name.toLowerCase()} op?`,
    included: (name: string) => `${name}: wat erbij hoort`,
    all: 'Alle expertises',
  },
  notes: { all: 'Alles', filter: 'Filter op soort', read: 'lezen', schemaName: 'Het Journaal · Not by Accident' },
  note: { next: 'Volgende notitie', published: 'Gepubliceerd', video: 'Ingesloten video' },
  trainings: { thanks: 'Je staat op de lijst. We schrijven zodra de data vaststaan.' },
  reports: { thanks: 'Dank je. We schrijven zodra het eerste rapport online staat.', meanwhile: 'Lees intussen de notities' },
  contact: {
    direct: 'Rechtstreeks',
    hours: 'Openingstijden',
    name: 'Naam',
    nameHelp: 'Zodat we weten aan wie we schrijven.',
    company: 'Bedrijf',
    companyHelp: 'Optioneel.',
    email: 'E-mail',
    emailHelp: 'We antwoorden hier, nergens anders.',
    budget: 'Globaal budget',
    budgetHelp: 'Een bandbreedte is genoeg. Weet je het nog niet, prima.',
    budgetPick: 'Kies een bandbreedte',
    budgetOptions: ['Onder £25.000', '£25.000–£75.000', '£75.000–£150.000', '£150.000–£300.000', 'Boven £300.000', 'Nog niet zeker'],
    message: 'Waar werk je aan?',
    messageHelp: 'Het bedrijf, en wat je wilt veranderen. Specifiek wint van lang.',
    send: 'Versturen',
    thanks: 'Dank je. Een mens antwoordt binnen één werkdag.',
  },
  search: {
    seoTitle: 'Zoeken',
    seoDescription: 'Doorzoek Not by Accident: werk, expertises en notities.',
    h1: 'Zoeken',
    label: 'Doorzoek de site',
    placeholder: 'Een project, een notitie, een discipline…',
    idle: 'Typ om cases, notities en expertises te doorzoeken.',
    results: (n: number, q: string) => `${n} ${n === 1 ? 'resultaat' : 'resultaten'} voor “${q}”`,
    empty: 'Hier past nog niets bij. Probeer een breder woord, of begin bij',
    kinds: { page: 'Pagina', capability: 'Expertise', case: 'Case', note: 'Notitie' },
  },
  privacy: { updated: 'Laatst bijgewerkt', onThisPage: 'Op deze pagina', questions: 'Vragen hierover? Schrijf naar' },
  cookies: { category: 'Categorie', does: 'Wat het doet', lifespan: 'Bewaartermijn', fuller: 'Voor het volledige beeld van wat we bewaren en waarom, zie de', privacyLink: 'privacyverklaring' },
  notFound: { tidy: 'Zet het terug', untidy: 'Ongedaan maken', home: 'Naar home', work: 'Bekijk het werk', hint: 'Sleep de letters, of zet ze terug op volgorde.' },
}
