/* Writes supabase/migrations/0010_next_site.sql from src/content/sections.en.ts.
   Run after changing the English defaults:  node scripts/generate-next-seed.ts
   The migration is idempotent and additive: it creates nothing that exists,
   overwrites no row, and never touches the previous site's pages. */
import { writeFileSync } from 'node:fs'
import { sectionsEn as allSections, pageMetaEn as allMeta } from '../src/content/sections.en.ts'

// 0010 is applied in production and must not change. The Lab's pages, its
// homepage section and its menu entries are seeded by 0014 instead
// (scripts/generate-lab-content.ts), so they are filtered out here.
const LAB = new Set(['lab', 'lab-how', 'lab-readiness', 'lab-app'])
const sectionsEn = Object.fromEntries(
  Object.entries(allSections)
    .filter(([slug]) => !LAB.has(slug))
    .map(([slug, page]) => [
      slug,
      Object.fromEntries(
        Object.entries(page)
          .filter(([key]) => !(slug === 'home' && key === 'lab'))
          .map(([key, sec]) => [key, sec.items ? { ...sec, items: sec.items.filter(it => it.body !== '/lab') } : sec]),
      ),
    ]),
) as typeof allSections
const pageMetaEn = Object.fromEntries(Object.entries(allMeta).filter(([slug]) => !LAB.has(slug))) as typeof allMeta

const q = (v: unknown) => (v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`

const schema = `-- 0010 · The new site (notbyaccident-next)
--
-- Additive and idempotent. Safe to run on the production project that the
-- previous site also reads: the new site's page copy lives in its own
-- pages (slug prefix "next/"), so the previous site's "home", "studio" …
-- rows are never touched. Re-running changes nothing.
--
-- Generated by scripts/generate-next-seed.ts from src/content/sections.en.ts.

-- ── category_meta ─────────────────────────────────────────────────────────
-- Read by the admin's Categories screen and both public sites, but never
-- created by a migration. Created here if missing.
create table if not exists public.category_meta (
  key text primary key check (key in ('Brand & Identity', 'Digital & Product', 'Growth & Demand', 'Market & Expansion', 'Experiences')),
  label text not null,
  blurb text,
  accent text not null default '#6E2237',
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);
alter table public.category_meta enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'category_meta' and policyname = 'category_meta_public_read') then
    create policy "category_meta_public_read" on public.category_meta for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'category_meta' and policyname = 'category_meta_staff_write') then
    create policy "category_meta_staff_write" on public.category_meta for all using (public.is_staff()) with check (public.is_staff());
  end if;
end $$;
insert into public.category_meta (key, label, blurb, accent, sort_order) values
  ('Brand & Identity', 'Brand & Identity', 'What the company is, and how it looks, sounds and behaves.', '#6E2237', 0),
  ('Digital & Product', 'Digital & Product', 'Where people meet it, and decide.', '#6A6383', 1),
  ('Growth & Demand', 'Growth & Demand', 'How it gets wanted, at scale.', '#7F8B3E', 2),
  ('Market & Expansion', 'Market & Expansion', 'Where it goes next, and who it needs to convince to get there.', '#C08A1E', 3),
  ('Experiences', 'Experiences', 'Where the brand happens in a room, not a browser.', '#221E1B', 4)
on conflict (key) do nothing;

-- ── SEO and media fields the new site edits ───────────────────────────────
alter table public.pages add column if not exists og_title text;
alter table public.pages add column if not exists og_description text;

alter table public.projects add column if not exists hero_video_url text;
alter table public.projects add column if not exists og_title text;
alter table public.projects add column if not exists og_description text;

alter table public.articles add column if not exists og_title text;
alter table public.articles add column if not exists og_description text;

alter table public.capabilities add column if not exists seo_title text;
alter table public.capabilities add column if not exists seo_description text;
alter table public.capabilities add column if not exists og_media_id uuid references public.media (id) on delete set null;
alter table public.capabilities add column if not exists canonical_url text;
alter table public.capabilities add column if not exists noindex boolean not null default false;

-- ── Seed media for the default page imagery (external URLs) ───────────────
`

const media = new Map<string, string>()
for (const page of Object.values(sectionsEn)) for (const s of Object.values(page)) if (s.image?.url) media.set(s.image.url, s.image.alt)

const mediaSql = media.size
  ? `insert into public.media (bucket, storage_path, file_type, file_name, alt_text) values\n${[...media]
      .map(([url, alt]) => `  ('external', ${q(url)}, 'image', ${q(url.split('/').pop()!.split('?')[0])}, ${q(alt)})`)
      .join(',\n')}\non conflict (bucket, storage_path) do nothing;\n`
  : ''

const pagesSql =
  `\n-- ── The new site's pages (SEO defaults per page) ──────────────────────────\ninsert into public.pages (slug, title, seo_title, seo_description) values\n` +
  Object.entries(pageMetaEn)
    .map(([slug, m]) => `  ('next/${slug}', ${q(slug === 'home' ? 'Homepage' : slug === 'global' ? 'Global (header, footer)' : slug)}, ${q(m.title)}, ${q(m.description)})`)
    .join(',\n') +
  `\non conflict (slug) do nothing;\n`

let sectionsSql = `\n-- ── Their sections ────────────────────────────────────────────────────────\n`
for (const [slug, sections] of Object.entries(sectionsEn)) {
  Object.entries(sections).forEach(([key, s], i) => {
    const extra = { ...(s.extra ?? {}), ...(s.items ? { items: s.items } : {}) }
    const image = s.image?.url ? `(select id from public.media where bucket = 'external' and storage_path = ${q(s.image.url)})` : 'null'
    sectionsSql += `insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, ${q(key)}, ${q(s.eyebrow)}, ${q(s.title)}, ${q(s.subtitle)}, ${q(s.body)}, ${q(s.ctaLabel)}, ${q(s.ctaUrl)}, ${image}, ${q(s.videoUrl)}, ${i}, ${j(extra)}
from public.pages where slug = 'next/${slug}'
on conflict (page_id, section_key) do nothing;\n`
  })
}

// The announcement bar starts hidden.
sectionsSql += `update public.page_sections set is_visible = false
where section_key = 'announcement' and page_id = (select id from public.pages where slug = 'next/global') and coalesce(title, '') = '';\n`

const out = new URL('../supabase/migrations/0010_next_site.sql', import.meta.url)
writeFileSync(out, schema + mediaSql + pagesSql + sectionsSql)
console.log('wrote', out.pathname)
