/* Writes supabase/migrations/0014_lab_content.sql from src/content/sections.en.ts:
   the Lab's public pages, its in-app microcopy, the homepage "The Lab"
   section and a "The Lab" entry in the header and footer menus.
   Run after changing the Lab's English defaults:  node scripts/generate-lab-content.ts
   Additive and idempotent: nothing an editor has changed is overwritten; the
   menu entries are appended only when no /lab link exists yet. */
import { writeFileSync } from 'node:fs'
import { sectionsEn, pageMetaEn } from '../src/content/sections.en.ts'
import type { PageSlug, SectionContent } from '../src/content/types.ts'

const q = (v: unknown) => (v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`

const LAB_PAGES: PageSlug[] = ['lab', 'lab-how', 'lab-readiness', 'lab-app']
const TITLES: Record<string, string> = { lab: 'The Lab', 'lab-how': 'The Lab · How it works', 'lab-readiness': 'The Lab · Readiness preview', 'lab-app': 'The Lab · App microcopy' }

const section = (slug: string, key: string, s: SectionContent, i: number) => {
  const extra = { ...(s.extra ?? {}), ...(s.items ? { items: s.items } : {}) }
  return `insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, ${q(key)}, ${q(s.eyebrow)}, ${q(s.title)}, ${q(s.subtitle)}, ${q(s.body)}, ${q(s.ctaLabel)}, ${q(s.ctaUrl)}, null, ${q(s.videoUrl)}, ${i}, ${j(extra)}
from public.pages where slug = 'next/${slug}'
on conflict (page_id, section_key) do nothing;\n`
}

let sql = `-- 0014 · THE LAB — editable content
--
-- The Lab's public pages and in-app copy, as CMS pages (next/lab…) that
-- Admin → Pages edits like every other page; the homepage's "The Lab"
-- section; and a "The Lab" menu entry. Additive and idempotent.
--
-- Generated by scripts/generate-lab-content.ts from src/content/sections.en.ts.

insert into public.pages (slug, title, seo_title, seo_description, noindex) values
${LAB_PAGES.map(slug => `  ('next/${slug}', ${q(TITLES[slug])}, ${q(pageMetaEn[slug].title)}, ${q(pageMetaEn[slug].description)}, ${slug === 'lab-app' ? 'true' : 'false'})`).join(',\n')}
on conflict (slug) do nothing;

`
for (const slug of LAB_PAGES) {
  Object.entries(sectionsEn[slug]).forEach(([key, s], i) => (sql += section(slug, key, s, i)))
}

// The homepage section, placed after "practice" in sort order.
sql += `\n-- ── Homepage: The Lab ──\n` + section('home', 'lab', sectionsEn.home.lab!, 3)

sql += `
-- ── Menus: append "The Lab" once ──
update public.page_sections ps
set extra = jsonb_set(coalesce(ps.extra, '{}'::jsonb), '{items}', coalesce(ps.extra->'items', '[]'::jsonb) || '[{"title":"The Lab","body":"/lab"}]'::jsonb)
from public.pages p
where p.id = ps.page_id and p.slug = 'next/global' and ps.section_key in ('header_nav', 'footer_nav')
  and not exists (select 1 from jsonb_array_elements(coalesce(ps.extra->'items', '[]'::jsonb)) it where it->>'body' = '/lab');
`

const out = new URL('../supabase/migrations/0014_lab_content.sql', import.meta.url)
writeFileSync(out, sql)
console.log('wrote', out.pathname)
