-- ============================================================================
-- NOT BY ACCIDENT — SEED DATA
-- ============================================================================
-- Auto-generated from src/data.ts by scripts/generate-seed-sql.mjs — do not
-- hand-edit; re-run the script instead if the static content changes.
-- Run this AFTER 0001_init.sql. Safe to re-run (upserts on the natural key).
--
-- This seeds published content for capabilities, projects/case studies,
-- articles/notes, testimonials, clients, partners and team members. Image
-- URLs are stored directly on a "media" row pointing at the existing Unsplash
-- URLs (file_type left as 'image', bucket left null) so the site keeps
-- working immediately — replace them with real uploads from the Media
-- Library whenever you're ready; nothing forces you to do that on day one.
-- ============================================================================

-- Capabilities
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('brand-strategy', 'Brand Strategy', 'Brand & Identity', 'The commercial logic underneath the brand — what you sell, to whom, and why it wins.', 'Brand strategy is not a mood. It is the argument for why a company deserves to exist, priced correctly, in a market that already has enough. We build that argument first, because every downstream decision — identity, product, pricing, media — is cheaper and sharper once it exists.', ARRAY['Audience and demand mapping', 'Proposition and value articulation', 'Brand architecture', 'Competitive and category analysis']::text[], 'Why should anyone choose us, and pay what we are worth?', 'A written, agreed strategy that makes the next hundred decisions faster.', ARRAY['what is brand strategy', 'brand strategy agency Amsterdam', 'how to position a brand', 'brand strategy vs marketing strategy']::text[], 0, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('brand-positioning', 'Brand Positioning', 'Brand & Identity', 'The single space you own in a buyer’s mind — defended with evidence, not adjectives.', 'Most companies are positioned by accident: by whoever spoke loudest in the last workshop. We find the position that is both true and unoccupied, then make it defensible — so the market files you under a category of one.', ARRAY['Category and frame-of-reference definition', 'Point-of-difference and proof', 'Positioning statement and messaging house', 'Migration plan from where you are today']::text[], 'What do we want to be the obvious choice for?', 'A position competitors cannot copy without becoming you.', ARRAY['brand positioning', 'how to reposition a company', 'positioning statement examples', 'category of one strategy']::text[], 1, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('naming', 'Naming', 'Brand & Identity', 'Names for companies, products and ranges — decided, not voted on.', 'A name is a bet on a set of values that do not yet exist in the market. We do not hand over a list of four hundred and ask you to choose. We make a decision, defend it linguistically and legally, and give you the story that makes it stick.', ARRAY['Naming strategy and territories', 'Creation and shortlisting', 'Linguistic and trademark screening', 'Rationale and rollout language']::text[], 'What should this be called, and can we own it?', 'A name you can register, defend and grow into.', ARRAY['brand naming agency', 'how to name a company', 'product naming process', 'is my brand name available']::text[], 2, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('brand-architecture', 'Brand Architecture', 'Brand & Identity', 'How a company organises its brands, sub-brands and products so growth adds clarity instead of confusion.', 'Every company eventually has more than one thing to name — a new range, a new market, a new venue. Brand architecture is the decision system that determines what gets its own name, what borrows the parent’s, and how the whole family stays legible as it grows.', ARRAY['Portfolio and structure audit', 'Master-brand vs sub-brand decisions', 'Naming and nomenclature rules', 'Roll-out governance']::text[], 'When we launch the next thing, does it strengthen us or dilute us?', 'A structure that scales without a rename every eighteen months.', ARRAY['brand architecture strategy', 'sub brand vs master brand', 'brand portfolio strategy', 'how to name a product line']::text[], 3, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('brand-identity', 'Visual Identity', 'Brand & Identity', 'A complete visual system — logo, type, colour, layout — that survives without the logo.', 'Recognition does not come from a logo. It comes from a set of codes so consistent that the brand is legible even when the name is missing. We build that system and the guidelines that keep it alive.', ARRAY['Logo, symbol and lockups', 'Type, colour and layout systems', 'Art direction and iconography', 'Brand guidelines and asset libraries']::text[], 'What makes us unmistakable at a glance?', 'A system your team can run without us in the room.', ARRAY['visual identity design', 'brand identity system', 'logo and brand guidelines', 'rebrand agency']::text[], 4, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('verbal-identity', 'Verbal Identity', 'Brand & Identity', 'The words that only your company would use — tone, vocabulary and the rules that keep them consistent.', 'A visual system tells you what a brand looks like. A verbal identity tells you what it sounds like — the vocabulary it reaches for, the jokes it does and does not make, the sentence length that feels like it. We write the rules, then write the first hundred examples so the team can hear the difference.', ARRAY['Tone of voice principles', 'Vocabulary and lexicon', 'Messaging house and headline library', 'Copy guidelines and training']::text[], 'Would someone recognise our writing with the logo removed?', 'A voice specific enough to be worth protecting.', ARRAY['brand tone of voice', 'verbal identity guidelines', 'brand messaging framework', 'how to write brand voice guidelines']::text[], 5, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('creative-direction', 'Creative Direction', 'Brand & Identity', 'The taste and judgement that hold a brand together across everything it makes.', 'Creative direction is editing at the level of the whole company: photography, tone, campaigns and the thousand small calls that decide whether a brand feels considered or assembled. We hold the line so the work stays coherent as it scales.', ARRAY['Art and photography direction', 'Campaign concepting', 'Tone and creative governance', 'Production oversight']::text[], 'Does everything we make feel like us?', 'Work that is unmistakably one company, at any volume.', ARRAY['creative direction agency', 'art direction for brands', 'campaign creative direction', 'photography direction']::text[], 6, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('packaging', 'Packaging', 'Brand & Identity', 'Structural and graphic packaging design that earns the price on the shelf, not just on the screen.', 'Packaging is the one piece of brand work a customer actually holds. We design structure and graphics together, so the object argues for the price before anyone reads a word — and works just as hard photographed for a feed as it does on a shelf.', ARRAY['Structural and dieline design', 'Materials and print production', 'Range and variant systems', 'Sustainability and cost engineering']::text[], 'Does holding this make the price feel correct?', 'Packaging that reads as considered, not decorated.', ARRAY['packaging design agency', 'product packaging design', 'sustainable packaging design', 'FMCG packaging design']::text[], 7, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('web-design-development', 'Website Design & Development', 'Digital & Product', 'Websites that load fast, read clearly to search and AI crawlers, and move people towards a decision.', 'A website is where most people decide whether to trust you. We design and build sites that load fast, read well to search engines and AI crawlers, and move visitors towards a decision — without ever looking like a template.', ARRAY['Design and art direction', 'Front-end build and CMS', 'Core Web Vitals and performance', 'Schema, semantics and accessibility']::text[], 'Does our website earn trust and enquiries?', 'A site that ranks, converts and is easy to keep alive.', ARRAY['website design agency', 'high converting website design', 'SEO friendly web design', 'CMS website build']::text[], 8, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('ux-ui-design', 'UX/UI Design', 'Digital & Product', 'Interfaces people understand instantly and enjoy using.', 'Good UX is invisible; bad UX is a leak in the funnel. We design flows, screens and systems that reduce friction, respect attention and hold up under real use — measured, not asserted.', ARRAY['User research and flows', 'Interface and interaction design', 'Design systems and components', 'Usability testing']::text[], 'Can people do what they came to do, easily?', 'Fewer drop-offs, more completed actions.', ARRAY['UX UI design agency', 'product design services', 'usability testing', 'design system build']::text[], 9, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('digital-product-design', 'Digital Product Design', 'Digital & Product', 'Apps, platforms and tools designed and engineered end to end.', 'Some brands need more than a website — they need a product. We take digital products from concept to shipped, joining design and engineering so the thing you launch is the thing you argued for.', ARRAY['Product strategy and scoping', 'Design and prototyping', 'Full-stack engineering', 'Iteration and roadmap']::text[], 'What should we build, and can you build it?', 'A product in market, not a prototype in a drawer.', ARRAY['digital product design agency', 'app design and development', 'MVP build', 'product engineering studio']::text[], 10, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('ecommerce', 'E-commerce', 'Digital & Product', 'Storefronts and checkout experiences built to convert, not just to display a catalogue.', 'An e-commerce site is a sales floor with the lighting, the queue and the assistant all designed at once. We build storefronts, product pages and checkout flows tuned for conversion and repeat purchase, on the platform that actually suits the business.', ARRAY['Platform selection and build', 'Product and category page design', 'Checkout and conversion optimisation', 'Merchandising and CRO testing']::text[], 'Is the path from interest to purchase as short as it should be?', 'A storefront that turns browsing into buying.', ARRAY['ecommerce website design', 'Shopify agency', 'conversion rate optimisation ecommerce', 'ecommerce UX design']::text[], 11, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('growth-strategy', 'Growth Strategy', 'Growth & Demand', 'The plan that connects brand, product and demand into one commercial engine.', 'Growth is not a department. It is what happens when the brand, the product and the demand generation agree on the same story and the same numbers. We build the plan that holds all three together, with the channels, sequencing and targets to prove it is working.', ARRAY['Growth model and channel mix', 'Funnel and conversion mapping', 'Prioritisation and testing roadmap', 'Reporting and commercial targets']::text[], 'What is actually going to move revenue, in what order?', 'One growth plan the whole company can work from.', ARRAY['growth strategy agency', 'growth marketing strategy', 'how to build a growth plan', 'brand and demand alignment']::text[], 12, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('performance-marketing', 'Performance Marketing', 'Growth & Demand', 'Paid acquisition that respects the brand and the P&L in equal measure.', 'Performance without brand burns cash; brand without performance starves. We run paid media as one system with your brand — creative that could only be you, targeting that is not lazy, and reporting you can actually act on.', ARRAY['Paid search, social and display', 'Creative testing frameworks', 'Measurement and attribution', 'Budget and bid strategy']::text[], 'Is every pound of media working as hard as it could?', 'Acquisition economics that improve as you scale.', ARRAY['performance marketing agency', 'paid media management', 'PPC agency', 'growth marketing']::text[], 13, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('seo', 'SEO', 'Growth & Demand', 'Technical, content and entity SEO built for Google and AI answer engines.', 'Search in 2026 is two games at once: ranking in Google and being the source an AI answer quotes. We do both — technical foundations, semantic content and entity authority — so you show up where the decision is actually being made.', ARRAY['Technical SEO and Core Web Vitals', 'Entity and topical authority', 'On-page and content optimisation', 'AI-search and answer-engine optimisation']::text[], 'Do we show up when it matters, in search and in AI answers?', 'Qualified traffic that arrives ready to enquire.', ARRAY['SEO agency 2026', 'AI search optimisation', 'answer engine optimisation', 'entity SEO', 'how to rank in ChatGPT and Perplexity']::text[], 14, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('content-strategy', 'Content Strategy & Content Management', 'Growth & Demand', 'What to say, where and why — plus the operating system that keeps it published on time.', 'Content is how a brand earns attention between purchases. We define the themes you can credibly own, the formats that suit each channel, the semantic structure that gets you cited by search and AI, and the calendar and workflow that make it sustainable rather than sporadic.', ARRAY['Editorial strategy and pillars', 'Topic and entity mapping for SEO', 'Content operations and calendar', 'Measurement and iteration']::text[], 'What should we publish, and can we actually keep it up?', 'A content engine that compounds instead of resets.', ARRAY['content strategy agency', 'SEO content strategy', 'editorial strategy for brands', 'content management for AI search']::text[], 15, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('social-media', 'Social Media Strategy & Management', 'Growth & Demand', 'A social presence with a point of view, run with the discipline of a publication.', 'Most brand social is a content calendar wearing a strategy costume. We start with what the brand actually has to say, choose the platforms worth the effort, and run the account like an editor would — consistent voice, considered pace, real engagement.', ARRAY['Platform and format strategy', 'Content planning and production', 'Community management', 'Analytics and iteration']::text[], 'Does our social output sound like anyone in particular?', 'A following that behaves like an audience, not a number.', ARRAY['social media strategy agency', 'social media management agency', 'brand social media strategy', 'organic social growth']::text[], 16, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('influencer-marketing', 'Influencer / Creator Marketing', 'Growth & Demand', 'Creator partnerships chosen for fit and trust, not follower counts.', 'The best creator partnerships feel like a recommendation, not an advert. We find the voices your audience already trusts, brief them properly, and build relationships that pay back beyond a single post.', ARRAY['Creator strategy and sourcing', 'Briefing and relationship management', 'Content rights and usage', 'Performance and measurement']::text[], 'Who does our audience believe, and how do we work with them well?', 'Partnerships that read as trust, not spend.', ARRAY['influencer marketing agency', 'creator partnerships', 'UGC strategy', 'how to run influencer campaigns']::text[], 17, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('email-marketing', 'Email Marketing', 'Growth & Demand', 'Lifecycle and CRM programmes that turn a list into revenue.', 'Email is the one channel you own. We design lifecycle programmes — welcome, nurture, retention, win-back — that sound like your brand and move numbers you can see in the dashboard by Friday.', ARRAY['Lifecycle and automation design', 'Segmentation and CRM strategy', 'Copy, design and templates', 'Testing and deliverability']::text[], 'Is our owned audience actually earning?', 'Revenue from people who already know you.', ARRAY['email marketing agency', 'CRM lifecycle marketing', 'klaviyo agency', 'retention marketing']::text[], 18, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('campaign-strategy', 'Campaign Strategy', 'Growth & Demand', 'The big idea and the media plan that gets it in front of the right people, on time.', 'A campaign is not a creative treatment looking for a channel plan. It is one idea, expressed correctly for each place it appears, with a media plan built around when and how your audience actually pays attention. We design both halves together.', ARRAY['Campaign idea and concept', 'Channel and media planning', 'Cross-format asset development', 'Flighting and measurement']::text[], 'What is the one idea, and where does it need to show up?', 'A campaign that feels planned, not scattered.', ARRAY['campaign strategy agency', 'integrated campaign planning', 'creative campaign development', 'media planning for brand campaigns']::text[], 19, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('market-research', 'Market Research', 'Market & Expansion', 'Evidence about buyers, categories and pricing — before the expensive decisions.', 'We research to decide, not to reassure. Qualitative depth where nuance matters, quantitative scale where confidence does, and a synthesis that actually changes what you build next.', ARRAY['Qualitative interviews and ethnography', 'Quantitative surveys and segmentation', 'Pricing and willingness-to-pay studies', 'Category and trend analysis']::text[], 'What do our buyers actually believe, and pay for?', 'Decisions grounded in evidence instead of the loudest opinion.', ARRAY['brand market research', 'customer segmentation study', 'pricing research', 'willingness to pay analysis']::text[], 20, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('go-to-market-strategy', 'Go-to-Market Strategy', 'Market & Expansion', 'The sequenced plan for launching or scaling — channels, message, motion and economics.', 'A great product with a vague go-to-market is a slow, expensive failure. We plan the launch as a commercial system: who hears first, what they hear, where the money goes, and how you know it is working within weeks rather than quarters.', ARRAY['Launch sequencing and phasing', 'Channel and message planning', 'Sales and marketing alignment', 'Metrics, targets and readiness']::text[], 'How do we launch this so it lands and pays back?', 'A launch plan with owners, dates and numbers attached.', ARRAY['go to market strategy', 'product launch plan', 'GTM strategy for startups', 'how to launch a brand']::text[], 21, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('b2b-partnerships', 'B2B Partnerships & Potential Client Meetings', 'Market & Expansion', 'Distribution through other companies — targeting, outreach and the meetings themselves.', 'Sometimes the fastest route to demand is someone else’s audience. We design and broker partnerships — co-marketing, channel, bundling — and, where useful, get in the room ourselves: identifying, approaching and meeting the businesses worth partnering with.', ARRAY['Partnership strategy and targeting', 'Outreach and deal shaping', 'Co-marketing programmes', 'Meeting preparation and facilitation']::text[], 'Whose audience should we borrow, and on what terms?', 'A distribution channel that is not more ad spend.', ARRAY['B2B partnership strategy', 'co-marketing agency', 'channel partnerships', 'strategic alliances']::text[], 22, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('market-entry', 'Market Entry', 'Market & Expansion', 'The research, positioning and plan for taking a brand into a new country or category.', 'A brand that works in one market does not automatically work in the next one. We assess demand, competition, regulation and cultural fit before recommending how — or whether — to enter, then build the localised positioning and plan to do it properly.', ARRAY['Market viability assessment', 'Competitive and regulatory landscape', 'Localised positioning and messaging', 'Entry sequencing and partners']::text[], 'Should we enter this market, and if so, how?', 'A market-entry plan grounded in evidence, not enthusiasm.', ARRAY['international market entry strategy', 'market expansion strategy', 'how to launch a brand in a new country', 'market entry consultancy']::text[], 23, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('investor-readiness', 'Investor Readiness & Investor Meetings', 'Market & Expansion', 'The narrative, deck and evidence that make a company fundable — and the meetings themselves.', 'Investors buy a story about the future, backed by proof from the present. We shape the equity story, sharpen the deck and pressure-test the numbers so the room leans in for the right reasons — and where it helps, we join the meetings themselves.', ARRAY['Equity story and narrative', 'Pitch deck design and copy', 'Data-room narrative support', 'Rehearsal, Q&A prep and investor meetings']::text[], 'Why is this the company to back, now?', 'A raise narrative that survives due diligence.', ARRAY['investor pitch deck agency', 'how to make a fundable pitch', 'equity story', 'seed round narrative']::text[], 24, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('growth-process-consultancy', 'Growth Process Consultancy', 'Market & Expansion', 'How the team actually plans, ships and measures growth work — not just what it should do next.', 'Sometimes the plan is right and the process around it is broken: nobody owns the roadmap, testing has no rhythm, and every quarter starts from a blank page. We audit how growth actually gets decided and shipped inside your company, then install a process your team keeps using after we leave.', ARRAY['Growth operating rhythm audit', 'Roadmap, ownership and reporting structure', 'Testing and prioritisation frameworks', 'Team training and handover']::text[], 'Is the bottleneck the strategy, or how we work?', 'A growth process the team runs without us.', ARRAY['growth process consulting', 'marketing operations consultancy', 'growth team operating model', 'how to build a growth roadmap']::text[], 25, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('events', 'Events', 'Experiences', 'Gatherings designed to build the brand in the room, not just fill a calendar.', 'Some brand-building only happens in person. We concept, design and produce events worth attending — launches, dinners, studio evenings — treating the room itself as a piece of creative work with a beginning, middle and end.', ARRAY['Event concept and identity', 'Guest experience design', 'Production and on-the-day delivery', 'Follow-up and measurement']::text[], 'What is worth gathering people for, and will they remember it?', 'A room that remembers you.', ARRAY['brand events agency', 'experiential marketing agency', 'launch event production', 'corporate event design']::text[], 26, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('exhibitions', 'Exhibitions', 'Experiences', 'Physical and pop-up spaces that let people encounter the brand as an object, not a screen.', 'An exhibition asks more of a brand than a stand ever does — it has to survive being walked around. We design exhibitions, installations and pop-ups that hold up in three dimensions, from spatial concept through to fabrication and install.', ARRAY['Spatial and exhibition concept', 'Graphic and environmental design', 'Fabrication and production management', 'Install and de-rig']::text[], 'Does the brand still feel like itself in a physical space?', 'A space people photograph without being asked to.', ARRAY['exhibition design agency', 'pop-up store design', 'brand installation design', 'trade show stand design']::text[], 27, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('workshops', 'Workshops', 'Experiences', 'Practical, small-group sessions that leave a team able to do more of the work themselves.', 'We run working sessions, not lectures — on positioning, naming, creative direction and the brief itself — built around your actual project, not a generic deck. Teams leave with a decision made, not just a framework explained.', ARRAY['Workshop design and facilitation', 'Pre-work and materials', 'Live decision-making sessions', 'Written outputs and next steps']::text[], 'What could this team decide for itself, with the right structure in the room?', 'A decision made, not just a framework explained.', ARRAY['brand strategy workshop', 'creative direction workshop', 'positioning workshop facilitation', 'in-house brand training']::text[], 28, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;
insert into public.capabilities (slug, name, category, summary, lede, includes, question, outcome, queries, sort_order, is_active)
values ('trainings', 'Trainings', 'Experiences', 'Longer-form, in-person training in brand strategy and creative direction — opening 2027.', 'Everything we have learned about brand strategy and creative direction, taught directly, over two days, to a small group. Not a webinar series. Not a certificate. The same thinking we charge clients for, taught in person.', ARRAY['Two-day in-person format', 'Maximum twelve participants', 'Brand Strategy and Creative Direction tracks', 'Amsterdam, plus one further city per year']::text[], 'Can the thinking behind the work be taught, not just delivered?', 'A room of people who can now do more of this themselves.', ARRAY['brand strategy training course', 'creative direction training', 'in person branding workshop 2027', 'Not by Accident trainings']::text[], 29, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, summary = excluded.summary, lede = excluded.lede, includes = excluded.includes, question = excluded.question, outcome = excluded.outcome, queries = excluded.queries, sort_order = excluded.sort_order;

-- External (Unsplash) image references, so seeded rows below have something to point at
insert into public.media (bucket, storage_path, file_type, file_name, alt_text)
values
  ('external', 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1675773051474-55c4b7d2cf53', null),
  ('external', 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=1600&h=1000&fit=crop&auto=format', 'image', 'photo-1675773051474-55c4b7d2cf53', null),
  ('external', 'https://images.unsplash.com/photo-1759050486852-fdfe2fdc7bea?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1759050486852-fdfe2fdc7bea', null),
  ('external', 'https://images.unsplash.com/photo-1759050486852-fdfe2fdc7bea?w=1600&h=1000&fit=crop&auto=format', 'image', 'photo-1759050486852-fdfe2fdc7bea', null),
  ('external', 'https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1617050318658-a9a3175e34cb', null),
  ('external', 'https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=1600&h=1000&fit=crop&auto=format', 'image', 'photo-1617050318658-a9a3175e34cb', null),
  ('external', 'https://images.unsplash.com/photo-1771440047944-0b5d792213a9?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1771440047944-0b5d792213a9', null),
  ('external', 'https://images.unsplash.com/photo-1771440047944-0b5d792213a9?w=1600&h=1000&fit=crop&auto=format', 'image', 'photo-1771440047944-0b5d792213a9', null),
  ('external', 'https://images.unsplash.com/photo-1771440048218-68069773fa81?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1771440048218-68069773fa81', null),
  ('external', 'https://images.unsplash.com/photo-1771440048218-68069773fa81?w=1600&h=1000&fit=crop&auto=format', 'image', 'photo-1771440048218-68069773fa81', null),
  ('external', 'https://images.unsplash.com/photo-1661178081018-d1b8e685ef10?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1661178081018-d1b8e685ef10', null),
  ('external', 'https://images.unsplash.com/photo-1636014724389-270c4e9c0100?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1636014724389-270c4e9c0100', null),
  ('external', 'https://images.unsplash.com/photo-1483366774565-c783b9f70e2c?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1483366774565-c783b9f70e2c', null),
  ('external', 'https://images.unsplash.com/photo-1654481414716-2f4ab5fe0fbe?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1654481414716-2f4ab5fe0fbe', null),
  ('external', 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1509228468518-180dd4864904', null),
  ('external', 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1441984904996-e0b6ba687e04', null),
  ('external', 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1495364141860-b0d03eccd065', null),
  ('external', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1524178232363-1fb2b075b655', null),
  ('external', 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1626785774573-4b799315345d', null),
  ('external', 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1455390582262-044cdead277a', null),
  ('external', 'https://images.unsplash.com/photo-1503694978374-8a2fa686963a?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1503694978374-8a2fa686963a', null),
  ('external', 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&h=800&fit=crop&auto=format', 'image', 'photo-1554224155-8d04cb21cd6c', null),
  ('external', 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=600&h=750&fit=crop&auto=format', 'image', 'photo-1675773051474-55c4b7d2cf53', null),
  ('external', 'https://images.unsplash.com/photo-1523908511403-7fc7b25592f4?w=600&h=750&fit=crop&auto=format', 'image', 'photo-1523908511403-7fc7b25592f4', null);
on conflict (bucket, storage_path) do nothing;

-- Projects / Case studies
insert into public.projects (
  title, client, slug, year, industry, location, short_description,
  challenge, insight, strategy, outcome, results, services,
  related_capability_slugs, hero_image_media_id, thumbnail_media_id,
  featured, sort_order, status, published_at
) values (
  'Lavanta', null, 'lavanta', '2024', null, 'London', 'A jewellery brand that was being admired and not bought.',
  'Lavanta came to us three years into existence with a clear problem: strong product, strong following, soft sales.', 'The brand was being admired, not bought — priced like affordable luxury when it was already being worn like an heirloom. The gap was never the product. It was the story people had no permission to tell about owning it.', 'We repositioned the brand around the idea of heirloom at a contemporary price point — not affordable luxury, but the last piece in a category of one — and rebuilt the identity, product and demand system around that single idea.', '+34% conversion in six months, and a waiting list for the new collection.', '+34% conversion in six months, and a waiting list.', ARRAY['Brand Strategy', 'Creative Direction', 'SEO', 'Growth Strategy']::text[],
  ARRAY['brand-strategy', 'creative-direction', 'seo', 'growth-strategy']::text[], (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=1600&h=1000&fit=crop&auto=format'), (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=1200&h=800&fit=crop&auto=format'),
  true, 01, 'published', now()
)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, challenge = excluded.challenge, insight = excluded.insight, strategy = excluded.strategy, outcome = excluded.outcome, results = excluded.results, services = excluded.services, related_capability_slugs = excluded.related_capability_slugs, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.projects (
  title, client, slug, year, industry, location, short_description,
  challenge, insight, strategy, outcome, results, services,
  related_capability_slugs, hero_image_media_id, thumbnail_media_id,
  featured, sort_order, status, published_at
) values (
  'Studio Marché', null, 'studio-marche', '2025', null, 'Paris', 'A market that needed to feel like it belonged to its neighbourhood.',
  'Studio Marché had been running for four years without ever answering the question most successful markets never ask: what are we, exactly?', 'Not the vendors, not the footfall — the market itself was the brand, and nobody had named it as one thing. Every stall had its own identity. The market had none.', 'We defined a position that made the market itself the brand, not the sum of what was sold there, then built the creative system and campaign that let every vendor sit inside it without losing their own voice.', 'Footfall up 22%, and a market that finally reads as one place.', 'Footfall up 22%, and a market that finally reads as one place.', ARRAY['Brand Strategy', 'Brand Positioning', 'Creative Direction', 'Campaign Strategy']::text[],
  ARRAY['brand-strategy', 'brand-positioning', 'creative-direction', 'campaign-strategy']::text[], (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1759050486852-fdfe2fdc7bea?w=1600&h=1000&fit=crop&auto=format'), (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1759050486852-fdfe2fdc7bea?w=1200&h=800&fit=crop&auto=format'),
  false, 02, 'published', now()
)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, challenge = excluded.challenge, insight = excluded.insight, strategy = excluded.strategy, outcome = excluded.outcome, results = excluded.results, services = excluded.services, related_capability_slugs = excluded.related_capability_slugs, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.projects (
  title, client, slug, year, industry, location, short_description,
  challenge, insight, strategy, outcome, results, services,
  related_capability_slugs, hero_image_media_id, thumbnail_media_id,
  featured, sort_order, status, published_at
) values (
  'Edde', null, 'edde', '2025', null, 'Berlin', 'A skincare brand built to age alongside its customers.',
  'Most skincare brands are afraid of ageing, and build their entire identity around reversing it. Edde''s customers were not afraid of it, and the brand did not yet reflect that.', 'Visible time was not something to hide from this audience. It was a credential — evidence of a life the product was there to support, not correct.', 'We built an identity and digital system that treated ageing as something to understand rather than reverse, from the language on the packaging to the words used on the product pages.', 'Repeat purchase up 41% among customers over fifty.', 'Repeat purchase up 41% among customers over fifty.', ARRAY['Visual Identity', 'Verbal Identity', 'Website Design & Development', 'UX/UI Design']::text[],
  ARRAY['brand-identity', 'verbal-identity', 'web-design-development', 'ux-ui-design']::text[], (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=1600&h=1000&fit=crop&auto=format'), (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?w=1200&h=800&fit=crop&auto=format'),
  false, 03, 'published', now()
)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, challenge = excluded.challenge, insight = excluded.insight, strategy = excluded.strategy, outcome = excluded.outcome, results = excluded.results, services = excluded.services, related_capability_slugs = excluded.related_capability_slugs, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.projects (
  title, client, slug, year, industry, location, short_description,
  challenge, insight, strategy, outcome, results, services,
  related_capability_slugs, hero_image_media_id, thumbnail_media_id,
  featured, sort_order, status, published_at
) values (
  'Hinterland', null, 'hinterland', '2025', null, 'Melbourne', 'A hospitality group that needed to mean something in three cities at once.',
  'Hinterland operated twelve venues across three cities. It was successful by most measures and unrecognisable as a single brand.', 'The problem was not inconsistency of taste — every venue looked considered on its own. It was the absence of a system that let them all be recognisably one company without being identical.', 'We built a brand architecture and identity system that could flex across formats — restaurant, bar, event space — while remaining unmistakably the same company, then rolled it out across all twelve venues.', 'One brand across twelve venues, three cities, no confusion.', 'One brand across twelve venues, three cities, no confusion.', ARRAY['Brand Strategy', 'Brand Architecture', 'Creative Direction', 'Campaign Strategy']::text[],
  ARRAY['brand-strategy', 'brand-architecture', 'creative-direction', 'campaign-strategy']::text[], (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1771440047944-0b5d792213a9?w=1600&h=1000&fit=crop&auto=format'), (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1771440047944-0b5d792213a9?w=1200&h=800&fit=crop&auto=format'),
  false, 04, 'published', now()
)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, challenge = excluded.challenge, insight = excluded.insight, strategy = excluded.strategy, outcome = excluded.outcome, results = excluded.results, services = excluded.services, related_capability_slugs = excluded.related_capability_slugs, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.projects (
  title, client, slug, year, industry, location, short_description,
  challenge, insight, strategy, outcome, results, services,
  related_capability_slugs, hero_image_media_id, thumbnail_media_id,
  featured, sort_order, status, published_at
) values (
  'Unnamed Project', null, 'unnamed-2026', '2026', null, 'Undisclosed', 'In progress. More when we can.',
  null, null, null, null, 'In progress. More when we can.', ARRAY['Brand Strategy']::text[],
  ARRAY['brand-strategy']::text[], (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1771440048218-68069773fa81?w=1600&h=1000&fit=crop&auto=format'), (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1771440048218-68069773fa81?w=1200&h=800&fit=crop&auto=format'),
  false, 05, 'published', now()
)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, challenge = excluded.challenge, insight = excluded.insight, strategy = excluded.strategy, outcome = excluded.outcome, results = excluded.results, services = excluded.services, related_capability_slugs = excluded.related_capability_slugs, featured = excluded.featured, sort_order = excluded.sort_order;

-- Article categories
insert into public.article_categories (name, slug) values ('Essay', 'essay') on conflict (name) do nothing;
insert into public.article_categories (name, slug) values ('Notes', 'notes') on conflict (name) do nothing;
insert into public.article_categories (name, slug) values ('Field notes', 'field-notes') on conflict (name) do nothing;

-- Articles / Notes
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'The brief is never the brief', 'the-brief-is-never-the-brief', 'Why the document handed to a creative company at the start of a project almost always describes the symptom, not the problem.', '[{"type":"paragraph","text":"There is a document that exists at the start of every brand project. It is usually twelve pages long. It has a section called ''Background'', a section called ''Objectives'', and a section called ''The Challenge''. It is called a brief."},{"type":"paragraph","text":"It is rarely a brief."},{"type":"paragraph","text":"What most clients hand over at the start of a project is a description of the effect of a problem they have not yet named. The brief says: our conversion rate is low. It says: people don''t understand what we sell. It says: we feel premium but our price point doesn''t reflect it."},{"type":"paragraph","text":"These are symptoms. The brief is a list of symptoms. The actual problem — the one that, if solved, makes all the symptoms go away — is never in the brief, because the client does not know what it is. If they knew, they would have fixed it already."},{"type":"paragraph","text":"This is not a criticism. It is the nature of the work. The brief exists to start a conversation, not to define the answer."},{"type":"paragraph","text":"A creative company that takes a brief literally is usually building the wrong thing. Not because the client is wrong, but because the client cannot see the shape of their own problem. That is what they are paying for."},{"type":"paragraph","text":"The first job of any strategy engagement is to translate the brief into the real question. This is harder than it sounds and takes longer than most clients expect. It is almost never appreciated until it is done."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1661178081018-d1b8e685ef10?w=1200&h=800&fit=crop&auto=format'), 8, 'published', '2026-07-03T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'What packaging actually does', 'what-packaging-actually-does', 'A note on the difference between packaging that looks expensive and packaging that makes a product cost more.', '[{"type":"paragraph","text":"Packaging has a job. Most packaging forgets what the job is."},{"type":"paragraph","text":"The job is not to look expensive. A thing that looks expensive is trying. The job is to make someone feel, at the moment they hold it, that the price they paid was correct. That the price was, in fact, conservative."},{"type":"paragraph","text":"This is a much harder thing to achieve, because it requires the packaging to communicate something true about the product rather than something aspirational about the brand. And most brands do not know something true about their product that is worth communicating. They know what category they are in. They know their USP. They do not know what makes their product genuinely different from the thing beside it on the shelf."},{"type":"paragraph","text":"Good packaging is the visual translation of product truth. When the truth is strong, the packaging can be minimal. When the truth is weak, no amount of embossing or weight of board will save it."}]'::jsonb,
  (select id from public.article_categories where name = 'Notes'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1636014724389-270c4e9c0100?w=1200&h=800&fit=crop&auto=format'), 5, 'published', '2026-06-18T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'Naming is not a creative exercise', 'naming-is-not-a-creative-exercise', 'On the misconception that a good brand name comes from a long list and a vote.', '[{"type":"paragraph","text":"Every naming project starts the same way. The client wants a list. The longer the list, the better. They believe that somewhere inside a list of four hundred names, the right one is hiding."},{"type":"paragraph","text":"It is not."},{"type":"paragraph","text":"A brand name is a bet on a set of values that do not yet exist in the market. It does not describe the company. It does not explain what the company sells. It is the beginning of a reputation, which means it only means something after years of work have made it mean something."},{"type":"paragraph","text":"What this means in practice is that the name almost never matters as much as the client thinks it does, and the process of naming almost always matters more. A naming process that requires everyone in the room to agree is a process designed to produce a mediocre outcome that offends no one."},{"type":"paragraph","text":"The best names come from a decision, not a consensus."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1483366774565-c783b9f70e2c?w=1200&h=800&fit=crop&auto=format'), 6, 'published', '2026-05-02T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'Why growth is a brand problem', 'why-growth-is-a-brand-problem', 'The point at which demand generation and brand strategy become the same discipline.', '[{"type":"paragraph","text":"There is a version of marketing that treats brand and demand as separate budgets with separate goals. Brand is what you spend on awareness. Demand is what you spend on conversion. The two teams meet monthly and disagree about attribution."},{"type":"paragraph","text":"This separation made some sense when media was expensive and brand building required years of patient investment. It makes less sense now, when the same piece of work can build awareness, generate desire and drive a transaction in a single scroll."},{"type":"paragraph","text":"The most commercially effective brands we have worked with do not separate these things. They understand that every touchpoint is simultaneously doing brand work and demand work. The distinction is a legacy of media planning, not a useful description of how people actually decide to buy something."},{"type":"paragraph","text":"Growth is a brand problem because desire is a brand outcome. You do not generate demand for something people do not want. You build wanting first. Growth comes next."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1654481414716-2f4ab5fe0fbe?w=1200&h=800&fit=crop&auto=format'), 7, 'published', '2026-04-14T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'The tyranny of the reference', 'the-tyranny-of-the-reference', 'Why the mood board a client arrives with is usually a description of the last brand that impressed them, not the one they should become.', '[{"type":"paragraph","text":"Every project begins with references. A folder, a board, a link to three companies the client admires. This is meant to be helpful, and sometimes it is. More often it is a quiet act of surrender."},{"type":"paragraph","text":"A reference is a description of a problem someone else already solved. It is the visible outcome of a strategy you cannot see, made for a company you are not. Borrowing the outcome without the strategy is how brands end up looking expensive and meaning nothing."},{"type":"paragraph","text":"The companies worth admiring did not arrive at their look by collecting references. They arrived at it by understanding something true about themselves that no one else could claim. The confidence you are responding to is not aesthetic. It is the confidence of a company that knows exactly what it is."},{"type":"paragraph","text":"So we take the references seriously — not as instructions, but as evidence. What is it, precisely, that you envy here? Nine times out of ten the answer is not the typeface or the palette. It is the certainty. And certainty cannot be referenced. It has to be earned."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1200&h=800&fit=crop&auto=format'), 6, 'published', '2026-04-09T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'Premium is a promise, not a finish', 'premium-is-a-promise-not-a-finish', 'On the difference between a brand that looks costly and a brand that behaves as though it is worth the money.', '[{"type":"paragraph","text":"Clients ask for premium the way they ask for the weather. As if it were a setting. Make it feel more premium — add some black, a serif, a little space."},{"type":"paragraph","text":"But premium is not a finish you apply at the end. It is a promise you keep at every point of contact, most of which have nothing to do with how anything looks. It is the speed of the reply. The quality of the box. The person who answers the phone. The fact that nothing is oversold and nothing disappoints."},{"type":"paragraph","text":"A brand feels expensive when the experience never once contradicts the price. The moment it does — a clumsy checkout, a cheap email, a promise not kept — the spell breaks, and no amount of gold foil will restore it."},{"type":"paragraph","text":"This is inconvenient, because it means premium is not something we can hand over in a deck. It is a standard the whole company has to hold, long after we have gone. Our job is to define that standard precisely enough that it can be defended. Keeping it is the client''s."}]'::jsonb,
  (select id from public.article_categories where name = 'Notes'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&h=800&fit=crop&auto=format'), 5, 'published', '2026-03-20T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'In defence of the slow project', 'in-defence-of-the-slow-project', 'Why the best brand work resists the timeline it was sold on, and what that actually costs.', '[{"type":"paragraph","text":"Every good project has a moment where it should slow down and almost never does. It is the moment after the research and before the making, when the honest answer is: we do not yet know what this is."},{"type":"paragraph","text":"The pressure at that point is enormous. There is a timeline. There are people waiting. There is a natural human urge to convert uncertainty into activity, to start producing something so that it at least looks like progress. This is how most projects go quietly wrong — not through bad work, but through work made too early, before the thinking had finished."},{"type":"paragraph","text":"The slow project is not slow because anyone is idle. It is slow because it refuses to make things it cannot yet justify. It holds the uncomfortable open question a few days longer than feels reasonable, because the alternative is to answer it badly and spend the next three months defending the answer."},{"type":"paragraph","text":"We are not romantic about time. Slow is expensive and we know it. But the most expensive thing a company can do is build the wrong brand quickly, then live inside it for a decade."}]'::jsonb,
  (select id from public.article_categories where name = 'Field notes'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=1200&h=800&fit=crop&auto=format'), 6, 'published', '2026-02-28T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'The audience is not everyone', 'the-audience-is-not-everyone', 'A note on why the instinct to appeal to more people is the surest way to move fewer of them.', '[{"type":"paragraph","text":"The most common note we receive on a piece of strategy is some version of: could this speak to more people? It is asked in good faith and it is almost always wrong."},{"type":"paragraph","text":"A brand that tries to be for everyone is legible to no one. It rounds off every edge that might have made someone choose it, in the hope of offending no one who might have walked past anyway. The result is a brand that is technically acceptable to a large group and genuinely wanted by none of it."},{"type":"paragraph","text":"Wanting is specific. It is the feeling that something was made for you, by people who understood you well enough to leave other people out. That feeling is impossible to manufacture at scale, and it is the only feeling that reliably moves someone from interest to purchase."},{"type":"paragraph","text":"So when we narrow the audience, we are not shrinking the opportunity. We are concentrating it. A brand that a small group cannot live without will always outgrow a brand that a large group can take or leave. Reach is a distribution problem. Desire is a definition problem. Solve the second one first."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=800&fit=crop&auto=format'), 5, 'published', '2026-02-11T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'A logo is the least of it', 'a-logo-is-the-least-of-it', 'Why the mark everyone argues about is the smallest decision in a brand, and the one that should be made last.', '[{"type":"paragraph","text":"The logo gets the meeting. It gets the revisions, the opinions, the person who was quiet all project suddenly finding their voice. It is the part everyone feels qualified to judge, because it is the part that looks like a decision."},{"type":"paragraph","text":"But a logo is a signature, and a signature only means something because of everything the person has done under it. On its own it is a shape. It acquires meaning through repetition, through the quality of the work it sits beside, through years of a company behaving consistently enough that the shape starts to stand for something."},{"type":"paragraph","text":"This is why we make it late, and quietly. By the time we design the mark, the hard decisions are already made — the position, the voice, the system. The logo just has to sit at the front of all that without contradicting it. When the thinking underneath is strong, almost any competent mark will do. When it is weak, no mark will save it."},{"type":"paragraph","text":"Spend the argument on the strategy. Let the logo be the easy part."}]'::jsonb,
  (select id from public.article_categories where name = 'Notes'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&h=800&fit=crop&auto=format'), 5, 'published', '2026-01-22T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'The cost of sounding like everyone', 'the-cost-of-sounding-like-everyone', 'On the strange comfort of the words every company uses, and the price of hiding inside them.', '[{"type":"paragraph","text":"Read enough brand copy and you start to notice it is all the same. Everyone is passionate. Everyone is innovative. Everyone puts the customer at the heart of everything they do. The words are so common they have stopped carrying information — they are noise dressed as meaning."},{"type":"paragraph","text":"Companies reach for these words because they are safe. Nobody was ever fired for calling their company innovative. But safe language has a cost that does not show up on any invoice: it makes you invisible. If you sound like everyone, you are asking to be remembered as no one."},{"type":"paragraph","text":"The alternative is frightening, because it requires saying something specific enough that some people will disagree. A real voice has edges. It leaves things out. It commits to a way of seeing the world that not everyone will share, which is exactly what makes the people who do share it feel found."},{"type":"paragraph","text":"We spend a lot of time deleting the words that could belong to anyone. What is left is usually smaller, plainer and far more yours."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&h=800&fit=crop&auto=format'), 6, 'published', '2026-01-08T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'Consistency is not repetition', 'consistency-is-not-repetition', 'The difference between a brand that feels coherent and one that is merely identical everywhere.', '[{"type":"paragraph","text":"Somewhere along the way, consistency came to mean sameness. Use the logo at this size. This blue, never that one. The same headline treatment on every surface. Guidelines became a list of prohibitions, and the brand became a thing you could break but never build."},{"type":"paragraph","text":"Real consistency is not about repeating the same elements. It is about repeating the same judgement. It is the reason two pieces made by different people, in different formats, years apart, still feel like they came from the same mind. That coherence does not come from locking everything down. It comes from everyone involved understanding what the brand is trying to be, so their thousand small decisions point the same way."},{"type":"paragraph","text":"Rigid brands look consistent in a grid and fall apart in the world, because the world always asks for something the guidelines did not anticipate. Coherent brands flex without losing themselves, because the thing holding them together was never the rules — it was the taste underneath the rules."},{"type":"paragraph","text":"Write down the judgement, not just the measurements."}]'::jsonb,
  (select id from public.article_categories where name = 'Field notes'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1503694978374-8a2fa686963a?w=1200&h=800&fit=crop&auto=format'), 6, 'published', '2025-12-17T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;
insert into public.articles (
  title, slug, excerpt, body, category_id, hero_image_media_id,
  reading_time_minutes, status, published_at
) values (
  'Say the price out loud', 'say-the-price-out-loud', 'Why a brand that is shy about what it costs is usually unsure of what it is worth.', '[{"type":"paragraph","text":"You can tell a lot about a company by how it behaves around its own price. The confident ones state it plainly and move on. The unsure ones bury it, gate it behind a form, surround it with justification, or avoid the subject until the last possible moment."},{"type":"paragraph","text":"Price is the clearest thing a brand ever says about itself. It is a claim about worth, made in public, that the whole experience then has to honour. A company that is nervous about its price is really telling you it is not sure the claim is true — and customers feel that hesitation long before they see a number."},{"type":"paragraph","text":"The work of brand is, in large part, the work of earning the right to a price and then having the nerve to name it. When the position is sharp and the experience is whole, the number stops feeling like a risk and starts feeling like a fact. Nothing signals confidence like a company that will simply tell you what it costs."},{"type":"paragraph","text":"If you cannot say the price out loud, the problem is rarely the price."}]'::jsonb,
  (select id from public.article_categories where name = 'Essay'),
  (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&h=800&fit=crop&auto=format'), 5, 'published', '2025-12-03T00:00:00.000Z'
)
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, reading_time_minutes = excluded.reading_time_minutes;

-- Testimonials
insert into public.testimonials (quote, person_name, role, company, sort_order, is_active)
values ('They found the sentence our whole company had been failing to say for six years. Everything after that was easier — the pricing, the hiring, the pitch.', 'Amara Devlin', 'Founder', 'Lavanta', 0, true)
on conflict (person_name, company) do nothing;
insert into public.testimonials (quote, person_name, role, company, sort_order, is_active)
values ('Most people arrive with a deck. They arrived with a question, and it turned out to be the only one that mattered. We are still using the answer.', 'Henri Vasseur', 'Managing Director', 'Studio Marché', 1, true)
on conflict (person_name, company) do nothing;
insert into public.testimonials (quote, person_name, role, company, sort_order, is_active)
values ('We had confused looking expensive with being wanted. They took the whole thing apart, kept the two things that were true, and built the rest around them.', 'Ingrid Solberg', 'Chief Executive', 'Edde', 2, true)
on conflict (person_name, company) do nothing;
insert into public.testimonials (quote, person_name, role, company, sort_order, is_active)
values ('The work was sharp, but the thing I did not expect was how commercial it was. Every decision came back to a number we could actually move.', 'Marcus Bianchi', 'Group Marketing Director', 'Hinterland', 3, true)
on conflict (person_name, company) do nothing;

-- Clients (typographic placeholders — replace logo_media_id once real logo files are uploaded)
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('Lavanta', 'Lavanta', 0, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('STUDIO MARCHÉ', 'STUDIO MARCHÉ', 1, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('edde', 'edde', 2, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('Hinterland', 'Hinterland', 3, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('VELA', 'VELA', 4, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('Roux', 'Roux', 5, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('SONDER', 'SONDER', 6, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('Maison Têtu', 'Maison Têtu', 7, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('Folio&Co', 'Folio&Co', 8, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('KŌAN', 'KŌAN', 9, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('The North Table', 'The North Table', 10, true) on conflict (company_name) do nothing;
insert into public.clients (company_name, alt_text, sort_order, is_active) values ('STRATUM', 'STRATUM', 11, true) on conflict (company_name) do nothing;

-- Partners
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Monotype', 'Monotype', 0, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('CONTRA', 'CONTRA', 1, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('It’s Nice That', 'It’s Nice That', 2, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Are.na', 'Are.na', 3, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Semi-Permanent', 'Semi-Permanent', 4, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Counter-Print', 'Counter-Print', 5, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Unit Editions', 'Unit Editions', 6, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Framestore', 'Framestore', 7, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('Riso&Ink', 'Riso&Ink', 8, true) on conflict (partner_name) do nothing;
insert into public.partners (partner_name, alt_text, sort_order, is_active) values ('The Gourmand', 'The Gourmand', 9, true) on conflict (partner_name) do nothing;

-- Team members
insert into public.team_members (name, role, bio, portrait_media_id, sort_order, is_active)
values ('Sara Okafor', 'Founding Partner, Strategy', 'Sara spent a decade in strategy consulting before concluding that brand and commercial thinking should be one discipline, not two. She built Not by Accident on that premise.', (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1675773051474-55c4b7d2cf53?w=600&h=750&fit=crop&auto=format'), 0, true)
on conflict (name) do nothing;
insert into public.team_members (name, role, bio, portrait_media_id, sort_order, is_active)
values ('Tomás Reyes', 'Founding Partner, Creative', 'Tomás ran creative for two decade-long stints at independent agencies in Amsterdam and São Paulo before deciding the work was better when the creative director also sat in on the strategy.', (select id from public.media where bucket = 'external' and storage_path = 'https://images.unsplash.com/photo-1523908511403-7fc7b25592f4?w=600&h=750&fit=crop&auto=format'), 1, true)
on conflict (name) do nothing;

-- Site settings (singleton)
update public.site_settings set
  site_name = 'Not by Accident',
  site_description = 'We make companies wanted. Growth is what happens next.',
  default_seo_title = 'Independent creative company, Amsterdam',
  contact_email = 'hello@notbyaccident.com',
  new_business_email = 'new@notbyaccident.com',
  press_email = 'press@notbyaccident.com',
  hours = 'Monday–Thursday, 10:00–17:00 CET',
  social_links = '[{"label":"LinkedIn","url":"https://linkedin.com/company/notbyaccident"},{"label":"Instagram","url":"https://instagram.com/notbyaccident"},{"label":"TikTok","url":"https://tiktok.com/@notbyaccident"},{"label":"Substack","url":"https://notbyaccident.substack.com"},{"label":"Are.na","url":"https://are.na/not-by-accident"},{"label":"Dribbble","url":"https://dribbble.com/notbyaccident"}]'::jsonb
where id = 1;

-- Header navigation
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Work', '/work', 0) on conflict (location, label) do nothing;
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Notes', '/notes', 1) on conflict (location, label) do nothing;
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Studio', '/studio', 2) on conflict (location, label) do nothing;
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Trainings', '/trainings', 3) on conflict (location, label) do nothing;
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Reports', '/reports', 4) on conflict (location, label) do nothing;
insert into public.navigation_items (location, label, url, sort_order) values ('header', 'Contact', '/contact', 5) on conflict (location, label) do nothing;

