-- 0012 · THE LAB — engine
--
-- Every number the Lab shows is computed here, server-side, from stored
-- answers and stored configuration. Functions are SECURITY DEFINER and check
-- the caller themselves: lab_is_member() for brand data, lab_is_admin() for
-- administration. Deterministic: the same inputs and the same configuration
-- version always give the same output. Nothing here is random, sampled or
-- generated by a language model.

-- ═════════════════════════════════════════════════════════════════════════
-- Shared helpers
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_require_member(p_brand uuid)
returns void language plpgsql stable security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'sign in first' using errcode = '28000'; end if;
  if not (public.lab_is_member(p_brand) or public.lab_is_admin()) then
    raise exception 'not your brand' using errcode = '42501';
  end if;
end $$;

create or replace function public.lab_require_admin()
returns void language plpgsql stable security definer set search_path = public as $$
begin
  if not public.lab_is_admin() then raise exception 'administrators only' using errcode = '42501'; end if;
end $$;

create or replace function public.lab_log(p_action text, p_entity text, p_entity_id text, p_detail jsonb default null)
returns void language sql security definer set search_path = public as $$
  insert into public.lab_audit (actor_id, action, entity, entity_id, detail) values (auth.uid(), p_action, p_entity, p_entity_id, p_detail);
$$;

create or replace function public.lab_notify(p_user uuid, p_brand uuid, p_kind text, p_title text, p_body text, p_link text)
returns void language sql security definer set search_path = public as $$
  insert into public.lab_notifications (user_id, brand_id, kind, title, body, link) values (p_user, p_brand, p_kind, p_title, p_body, p_link);
$$;

-- EU member states (2026). Used for one rule only: crossing the single
-- market's customs border adds work, in either direction.
create or replace function public.lab_in_eu(p_code text)
returns boolean language sql immutable as $$
  select p_code = any (array['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE']);
$$;

create or replace function public.lab_label(p_key text)
returns text language sql immutable as $$
  select initcap(replace(coalesce(p_key, ''), '_', ' '));
$$;

-- ═════════════════════════════════════════════════════════════════════════
-- Assessment: conditions and scoring
-- ═════════════════════════════════════════════════════════════════════════

-- A question's applies_if is a list of conditions that must all hold:
--   {"source":"brand","field":"offering","in":["physical","mixed"]}
--   {"source":"answer","question":"wholesale","in":["yes"],"not_in":["no"]}
-- Brand fields may be scalars or arrays; a missing value never satisfies "in".
create or replace function public.lab_condition_holds(p_cond jsonb, p_brand jsonb, p_answers jsonb)
returns boolean language plpgsql immutable as $$
declare c jsonb; vals text[]; nots text[]; arr text[]; f jsonb;
begin
  if p_cond is null or jsonb_typeof(p_cond) <> 'array' then return true; end if;
  for c in select value from jsonb_array_elements(p_cond) loop
    vals := array(select jsonb_array_elements_text(coalesce(c->'in', '[]'::jsonb)));
    nots := array(select jsonb_array_elements_text(coalesce(c->'not_in', '[]'::jsonb)));
    if c->>'source' = 'brand' then
      f := p_brand -> (c->>'field');
    elsif c->>'source' = 'answer' then
      f := p_answers -> (c->>'question');
    else
      continue;
    end if;
    if f is null or jsonb_typeof(f) = 'null' then
      arr := '{}';
    elsif jsonb_typeof(f) = 'array' then
      arr := array(select jsonb_array_elements_text(f));
    else
      arr := array[f #>> '{}'];
    end if;
    if array_length(vals, 1) is not null and not (arr && vals) then return false; end if;
    if array_length(nots, 1) is not null and (arr && nots) then return false; end if;
  end loop;
  return true;
end $$;

-- The scoring engine.
--   question score  single/scale: the chosen option's score (0–100)
--                   multi: the chosen options' scores added, capped at 100
--                   an is_na option: the question leaves the denominator
--   category score  Σ(weight × question score) ÷ Σ(weight) over answered,
--                   applicable, non-N/A questions; null when there are none
--   overall         Σ(category weight × category score) ÷ Σ(category weight)
--                   over categories that have a score; rounded to 0.1
--   band            the band whose [min, max+1) contains the overall score
-- Questions whose conditions don't hold are skipped entirely (not zeroes).
-- Conditions on answers only see answers to questions that applied, in
-- question order, so a removed branch can't leak into a later one.
create or replace function public.lab_score_core(p_version uuid, p_brand jsonb, p_answers jsonb)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v public.lab_assessment_versions;
  q record;
  eff jsonb := '{}'::jsonb;
  sel text[];
  n int; qscore numeric; na boolean; labels text[]; recs text[] := '{}'; qrecs text[];
  acc jsonb := '{}'::jsonb;
  contribs jsonb := '[]'::jsonb;
  applicable_keys text[] := '{}';
  missing text[] := '{}';
  total_answered int := 0; total_applicable int := 0;
  c text; cw numeric; raw numeric; num numeric := 0; den numeric := 0; overall numeric;
  cats jsonb := '{}'::jsonb; band jsonb;
begin
  select * into v from public.lab_assessment_versions where id = p_version;
  if v.id is null then raise exception 'unknown assessment version' using errcode = '22023'; end if;
  p_answers := coalesce(p_answers, '{}'::jsonb);

  for q in select * from public.lab_questions where version_id = p_version order by sort, key loop
    if not public.lab_condition_holds(q.applies_if, p_brand, eff) then continue; end if;
    total_applicable := total_applicable + 1;
    applicable_keys := applicable_keys || q.key;
    if not acc ? q.category then
      acc := acc || jsonb_build_object(q.category, jsonb_build_object('wsum', 0, 'wtot', 0, 'answered', 0, 'applicable', 0, 'na', 0, 'unanswered', 0));
    end if;
    acc := jsonb_set(acc, array[q.category, 'applicable'], to_jsonb((acc #>> array[q.category, 'applicable'])::int + 1));

    sel := '{}';
    if jsonb_typeof(p_answers -> q.key) = 'array' then
      sel := array(select distinct jsonb_array_elements_text(p_answers -> q.key));
    end if;
    select count(*), coalesce(bool_or(o.is_na), false),
           case when q.kind = 'multi' then least(100, coalesce(sum(o.score) filter (where not o.is_na), 0)) else max(o.score) filter (where not o.is_na) end,
           array_agg(o.label order by o.sort), array_remove(array_agg(o.recommendation_key), null)
      into n, na, qscore, labels, qrecs
      from public.lab_options o where o.question_id = q.id and o.key = any (sel);

    if n = 0 or (q.kind <> 'multi' and n > 1) then
      acc := jsonb_set(acc, array[q.category, 'unanswered'], to_jsonb((acc #>> array[q.category, 'unanswered'])::int + 1));
      if q.required then missing := missing || q.key; end if;
      continue;
    end if;

    eff := eff || jsonb_build_object(q.key, to_jsonb(sel));
    recs := recs || coalesce(qrecs, '{}');
    total_answered := total_answered + 1;
    acc := jsonb_set(acc, array[q.category, 'answered'], to_jsonb((acc #>> array[q.category, 'answered'])::int + 1));
    if na then
      acc := jsonb_set(acc, array[q.category, 'na'], to_jsonb((acc #>> array[q.category, 'na'])::int + 1));
      contribs := contribs || jsonb_build_object('key', q.key, 'category', q.category, 'prompt', q.prompt, 'na', true, 'weight', q.weight, 'options', to_jsonb(labels));
    else
      acc := jsonb_set(acc, array[q.category, 'wsum'], to_jsonb((acc #>> array[q.category, 'wsum'])::numeric + q.weight * qscore));
      acc := jsonb_set(acc, array[q.category, 'wtot'], to_jsonb((acc #>> array[q.category, 'wtot'])::numeric + q.weight));
      contribs := contribs || jsonb_build_object('key', q.key, 'category', q.category, 'prompt', q.prompt, 'na', false, 'score', qscore, 'weight', q.weight, 'options', to_jsonb(labels));
    end if;
  end loop;

  for c, cw in select key, value::numeric from jsonb_each_text(v.category_weights) loop
    raw := null;
    if acc ? c and (acc #>> array[c, 'wtot'])::numeric > 0 then
      raw := (acc #>> array[c, 'wsum'])::numeric / (acc #>> array[c, 'wtot'])::numeric;
      num := num + cw * raw;
      den := den + cw;
    end if;
    cats := cats || jsonb_build_object(c, jsonb_build_object(
      'score', round(raw, 1),
      'weight', cw,
      'answered', coalesce((acc #>> array[c, 'answered'])::int, 0),
      'applicable', coalesce((acc #>> array[c, 'applicable'])::int, 0),
      'na', coalesce((acc #>> array[c, 'na'])::int, 0),
      'unanswered', coalesce((acc #>> array[c, 'unanswered'])::int, 0)
    ));
  end loop;

  overall := case when den > 0 then round(num / den, 1) end;
  if overall is not null then
    select b into band from jsonb_array_elements(v.bands) b
    where overall >= (b->>'min')::numeric and overall < (b->>'max')::numeric + 1
    order by (b->>'min')::numeric limit 1;
  end if;

  return jsonb_build_object(
    'version_id', v.id, 'version', v.version,
    'overall', overall, 'band', band,
    'categories', cats, 'contributions', contribs,
    'weights', v.category_weights, 'bands', v.bands,
    'answered', total_answered, 'applicable', total_applicable,
    'applicable_keys', to_jsonb(applicable_keys), 'missing_required', to_jsonb(missing),
    'effective_answers', eff, 'recommendation_keys', to_jsonb(recs)
  );
end $$;

-- Recommendations for a computed score: rules whose condition holds, plus
-- rules named by a chosen option's recommendation_key.
create or replace function public.lab_recommend(p_score jsonb, p_brand jsonb)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare r record; hit boolean; cs numeric; out jsonb := '[]'::jsonb; cond jsonb; forced text[];
begin
  forced := array(select jsonb_array_elements_text(coalesce(p_score->'recommendation_keys', '[]'::jsonb)));
  for r in select * from public.lab_recommendation_rules where active order by priority desc, key loop
    cond := r.condition;
    hit := false;
    if cond->>'type' in ('category_below', 'category_at_least') then
      cs := (p_score #>> array['categories', cond->>'category', 'score'])::numeric;
      hit := cs is not null and case when cond->>'type' = 'category_below' then cs < (cond->>'value')::numeric else cs >= (cond->>'value')::numeric end;
    elsif cond->>'type' = 'overall_below' then
      hit := (p_score->>'overall') is not null and (p_score->>'overall')::numeric < (cond->>'value')::numeric;
    elsif cond->>'type' = 'overall_at_least' then
      hit := (p_score->>'overall') is not null and (p_score->>'overall')::numeric >= (cond->>'value')::numeric;
    elsif cond->>'type' = 'option_selected' then
      hit := coalesce((p_score #> array['effective_answers', cond->>'question']) ? (cond->>'option'), false);
    elsif cond->>'type' = 'brand_field' then
      hit := public.lab_condition_holds(jsonb_build_array(cond || '{"source":"brand"}'::jsonb), p_brand, '{}'::jsonb);
    end if;
    if r.key = any (forced) then hit := true; end if;
    if hit then
      out := out || jsonb_build_object('key', r.key, 'title', r.title, 'body', r.body, 'category', r.category, 'priority', r.priority, 'partner_types', to_jsonb(r.partner_types));
    end if;
  end loop;
  return out;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Assessment workflow (user-facing)
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_answers_of(p_assessment uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_object_agg(q.key, to_jsonb(r.option_keys)), '{}'::jsonb)
  from public.lab_responses r join public.lab_questions q on q.id = r.question_id
  where r.assessment_id = p_assessment;
$$;

-- Start (or resume) an assessment on the published version. With p_prefill
-- the answers of the brand's latest completed assessment are copied over
-- wherever the question and option keys still exist — the route to
-- recalculating after a change without retyping everything. Completed
-- assessments and their results are never modified.
create or replace function public.lab_start_assessment(p_brand uuid, p_prefill boolean default true)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_version uuid; v_prev uuid;
begin
  perform public.lab_require_member(p_brand);
  select id into v_id from public.lab_assessments where brand_id = p_brand and status = 'in_progress';
  if v_id is not null then return v_id; end if;
  select id into v_version from public.lab_assessment_versions where status = 'published';
  if v_version is null then raise exception 'no published assessment yet' using errcode = '22023'; end if;
  insert into public.lab_assessments (brand_id, version_id, started_by) values (p_brand, v_version, auth.uid()) returning id into v_id;
  if p_prefill then
    select id into v_prev from public.lab_assessments where brand_id = p_brand and status = 'completed' order by completed_at desc limit 1;
    if v_prev is not null then
      insert into public.lab_responses (assessment_id, question_id, option_keys)
      select v_id, nq.id, array(select k from unnest(r.option_keys) k where exists (select 1 from public.lab_options o where o.question_id = nq.id and o.key = k))
      from public.lab_responses r
      join public.lab_questions oq on oq.id = r.question_id
      join public.lab_questions nq on nq.version_id = v_version and nq.key = oq.key
      where r.assessment_id = v_prev
        and exists (select 1 from public.lab_options o where o.question_id = nq.id and o.key = any (r.option_keys));
    end if;
  end if;
  return v_id;
end $$;

-- Everything the assessment screen needs in one round trip: the version's
-- questions with options, which of them apply right now, the answers so far.
create or replace function public.lab_assessment_state(p_assessment uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare a public.lab_assessments; b public.lab_brands; s jsonb;
begin
  select * into a from public.lab_assessments where id = p_assessment;
  if a.id is null then raise exception 'assessment not found' using errcode = '22023'; end if;
  perform public.lab_require_member(a.brand_id);
  select * into b from public.lab_brands where id = a.brand_id;
  s := public.lab_score_core(a.version_id, to_jsonb(b), public.lab_answers_of(a.id));
  return jsonb_build_object(
    'assessment', to_jsonb(a),
    'answers', public.lab_answers_of(a.id),
    'applicable', s->'applicable_keys',
    'missing_required', s->'missing_required',
    'answered', s->'answered',
    'applicable_count', s->'applicable',
    'version', (select jsonb_build_object('id', v.id, 'version', v.version, 'title', v.title, 'weights', v.category_weights) from public.lab_assessment_versions v where v.id = a.version_id),
    'questions', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', q.id, 'key', q.key, 'category', q.category, 'kind', q.kind, 'prompt', q.prompt, 'help', q.help, 'why', q.why,
        'required', q.required, 'weight', q.weight, 'applies_if', q.applies_if,
        'options', (select coalesce(jsonb_agg(jsonb_build_object('key', o.key, 'label', o.label, 'is_na', o.is_na) order by o.sort, o.key), '[]'::jsonb) from public.lab_options o where o.question_id = q.id)
      ) order by q.sort, q.key), '[]'::jsonb)
      from public.lab_questions q where q.version_id = a.version_id
    )
  );
end $$;

create or replace function public.lab_save_answer(p_assessment uuid, p_question text, p_options text[])
returns jsonb language plpgsql security definer set search_path = public as $$
declare a public.lab_assessments; q public.lab_questions; n int; na_n int; b public.lab_brands; s jsonb;
begin
  select * into a from public.lab_assessments where id = p_assessment;
  if a.id is null then raise exception 'assessment not found' using errcode = '22023'; end if;
  perform public.lab_require_member(a.brand_id);
  if a.status <> 'in_progress' then raise exception 'this assessment is complete; start a new one to change answers' using errcode = '22023'; end if;
  select * into q from public.lab_questions where version_id = a.version_id and key = p_question;
  if q.id is null then raise exception 'unknown question %', p_question using errcode = '22023'; end if;

  if p_options is null or array_length(p_options, 1) is null then
    delete from public.lab_responses where assessment_id = a.id and question_id = q.id;
  else
    select count(*), count(*) filter (where is_na) into n, na_n from public.lab_options where question_id = q.id and key = any (p_options);
    if n <> (select count(distinct x) from unnest(p_options) x) then raise exception 'unknown option for %', p_question using errcode = '22023'; end if;
    if q.kind <> 'multi' and n <> 1 then raise exception '% takes exactly one answer', p_question using errcode = '22023'; end if;
    if na_n > 0 and n > 1 then raise exception '"does not apply" cannot be combined with other answers' using errcode = '22023'; end if;
    insert into public.lab_responses (assessment_id, question_id, option_keys) values (a.id, q.id, array(select distinct x from unnest(p_options) x))
    on conflict (assessment_id, question_id) do update set option_keys = excluded.option_keys, updated_at = now();
  end if;
  update public.lab_assessments set last_question_key = p_question, updated_at = now() where id = a.id;
  select * into b from public.lab_brands where id = a.brand_id;
  s := public.lab_score_core(a.version_id, to_jsonb(b), public.lab_answers_of(a.id));
  return jsonb_build_object('applicable', s->'applicable_keys', 'missing_required', s->'missing_required', 'answered', s->'answered', 'applicable_count', s->'applicable');
end $$;

create or replace function public.lab_complete_assessment(p_assessment uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare a public.lab_assessments; b public.lab_brands; s jsonb; recs jsonb; v_result uuid; r jsonb;
begin
  select * into a from public.lab_assessments where id = p_assessment for update;
  if a.id is null then raise exception 'assessment not found' using errcode = '22023'; end if;
  perform public.lab_require_member(a.brand_id);
  if a.status = 'completed' then
    return (select id from public.lab_results where assessment_id = a.id order by computed_at desc limit 1);
  end if;
  select * into b from public.lab_brands where id = a.brand_id;
  s := public.lab_score_core(a.version_id, to_jsonb(b), public.lab_answers_of(a.id));
  if jsonb_array_length(s->'missing_required') > 0 then
    raise exception 'answer the remaining questions first: %', (select string_agg(x, ', ') from jsonb_array_elements_text(s->'missing_required') x) using errcode = '22023';
  end if;
  insert into public.lab_results (assessment_id, brand_id, version_id, version, overall, band_key, band_label, categories, contributions, weights, bands, answered, applicable)
  values (a.id, a.brand_id, a.version_id, (s->>'version')::int, (s->>'overall')::numeric, s #>> '{band,key}', s #>> '{band,label}',
          s->'categories', s->'contributions', s->'weights', s->'bands', (s->>'answered')::int, (s->>'applicable')::int)
  returning id into v_result;
  recs := public.lab_recommend(s, to_jsonb(b));
  for r in select value from jsonb_array_elements(recs) loop
    insert into public.lab_result_recommendations (result_id, rule_key, title, body, category, priority, partner_types)
    values (v_result, r->>'key', r->>'title', r->>'body', r->>'category', (r->>'priority')::int, array(select jsonb_array_elements_text(r->'partner_types')));
  end loop;
  update public.lab_assessments set status = 'completed', completed_at = now(), updated_at = now() where id = a.id;
  return v_result;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Market fit and comparison
-- ═════════════════════════════════════════════════════════════════════════

-- One market for one brand. Every factor says where its evidence comes
-- from: self_reported (the brand's own answers), verified (the market
-- profile's recorded facts), database (our partner records) or rule (a
-- product rule applied to those). A score is only produced when the brand
-- has a completed assessment and at least three factors can be evaluated.
create or replace function public.lab_market_fit_one(p_brand public.lab_brands, p_code text, p_result public.lab_results)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  m public.lab_markets;
  factors jsonb := '[]'::jsonb; missing jsonb := '[]'::jsonb; considerations jsonb := '[]'::jsonb; steps jsonb := '[]'::jsonb;
  ops numeric; val numeric; partners int; num numeric := 0; den numeric := 0; scored int := 0; score numeric;
  lang_overlap boolean; crossing text; v_note text;
begin
  select * into m from public.lab_markets where code = p_code and (status = 'published' or public.lab_is_admin()) and (not is_fixture or public.lab_fixtures_visible());
  if m.code is null then
    return jsonb_build_object('code', p_code, 'status', 'unavailable', 'message', 'We have no published profile for this market yet.');
  end if;

  -- 1 · overall readiness (self-reported, weight 30)
  if p_result.id is not null and p_result.overall is not null then
    factors := factors || jsonb_build_object('key', 'readiness', 'label', 'Overall readiness', 'weight', 30, 'value', p_result.overall, 'evidence', 'self_reported',
      'note', 'Your latest readiness score (version ' || p_result.version || ').');
    num := num + 30 * p_result.overall; den := den + 30; scored := scored + 1;
  else
    missing := missing || to_jsonb('A completed readiness assessment'::text);
  end if;

  -- 2 · experience in this market (self-reported, weight 10)
  if m.code = any (p_brand.current_markets) then
    factors := factors || jsonb_build_object('key', 'experience', 'label', 'Existing presence', 'weight', 10, 'value', 100, 'evidence', 'self_reported', 'note', 'You already sell here.');
    num := num + 1000; den := den + 10; scored := scored + 1;
  else
    factors := factors || jsonb_build_object('key', 'experience', 'label', 'Existing presence', 'weight', 10, 'value', 40, 'evidence', 'self_reported', 'note', 'No recorded sales here yet.');
    num := num + 400; den := den + 10; scored := scored + 1;
  end if;

  -- 3 · language readiness (verified market languages × your materials, weight 15)
  if array_length(m.languages, 1) is null then
    missing := missing || to_jsonb('The market''s working languages'::text);
  elsif array_length(p_brand.languages, 1) is null then
    missing := missing || to_jsonb('The languages your product pages and packaging are ready in'::text);
  else
    lang_overlap := p_brand.languages && m.languages;
    val := case when lang_overlap then 100 else 35 end;
    factors := factors || jsonb_build_object('key', 'language', 'label', 'Language readiness', 'weight', 15, 'value', val, 'evidence', 'verified',
      'note', case when lang_overlap then 'Your materials already exist in a working language here.' else 'Your materials are not yet in a working language here (' || array_to_string(m.languages, ', ') || ').' end);
    num := num + 15 * val; den := den + 15; scored := scored + 1;
    if not lang_overlap then steps := steps || to_jsonb(('Localise product pages, packaging copy and sales material into ' || array_to_string(m.languages, ' or ') || '.')::text); end if;
  end if;

  -- 4 · logistics (self-reported operations score, adjusted by a customs rule, weight 15)
  ops := (p_result.categories #>> '{operations,score}')::numeric;
  if p_brand.offering in ('digital', 'service') then
    null; -- shipping doesn't apply
  elsif ops is null then
    missing := missing || to_jsonb('Operational readiness (answer the operations questions)'::text);
  else
    val := ops;
    if p_brand.origin_country is not null and public.lab_in_eu(p_brand.origin_country) <> public.lab_in_eu(m.code) then
      val := greatest(0, ops - 15);
      crossing := 'Shipping between ' || coalesce(p_brand.origin_country, '?') || ' and ' || m.code || ' crosses the EU customs border: duties, VAT handling and returns need planning.';
      considerations := considerations || jsonb_build_object('label', 'Customs', 'text', crossing, 'evidence', 'rule');
    end if;
    factors := factors || jsonb_build_object('key', 'logistics', 'label', 'Logistics capability', 'weight', 15, 'value', round(val, 1), 'evidence', case when crossing is null then 'self_reported' else 'rule' end,
      'note', coalesce(crossing, 'Based on your operations answers.'));
    num := num + 15 * val; den := den + 15; scored := scored + 1;
  end if;

  -- 5 · partners in our database for this market and category (weight 15)
  select count(*) into partners from public.lab_partners p
  where public.lab_partner_visible(p)
    and (p.country_code = m.code or exists (select 1 from public.lab_partner_markets pm where pm.partner_id = p.id and pm.market_code = m.code))
    and (array_length(p.industries, 1) is null or p_brand.industry = any (p.industries))
    and not (p_brand.industry = any (p.excluded_industries));
  val := case when partners = 0 then 0 when partners < 3 then 60 else 100 end;
  factors := factors || jsonb_build_object('key', 'partners', 'label', 'Partners in our database', 'weight', 15, 'value', val, 'evidence', 'database', 'count', partners,
    'note', case when partners = 0 then 'None recorded yet for your category. That says more about our database than about the market.' else partners || ' listed for your category.' end);
  num := num + 15 * val; den := den + 15; scored := scored + 1;
  if partners = 0 then steps := steps || to_jsonb('Ask us to research partners in this market (Matches → Request research).'::text); end if;

  -- verified intelligence, shown as considerations, never invented
  if m.logistics_notes is not null then considerations := considerations || jsonb_build_object('label', 'Logistics', 'text', m.logistics_notes, 'evidence', 'verified'); else missing := missing || to_jsonb('Verified logistics notes'::text); end if;
  if m.regulatory_notes is not null then considerations := considerations || jsonb_build_object('label', 'Regulation', 'text', m.regulatory_notes, 'evidence', 'verified'); else missing := missing || to_jsonb('Verified regulatory notes'::text); end if;
  if m.pricing_notes is not null then considerations := considerations || jsonb_build_object('label', 'Pricing', 'text', m.pricing_notes, 'evidence', 'verified'); else missing := missing || to_jsonb('Verified pricing benchmarks'::text); end if;
  if array_length(m.distribution_channels, 1) is not null then considerations := considerations || jsonb_build_object('label', 'Distribution', 'text', array_to_string(m.distribution_channels, ' · '), 'evidence', 'verified'); end if;
  if array_length(m.entry_barriers, 1) is not null then considerations := considerations || jsonb_build_object('label', 'Entry barriers', 'text', array_to_string(m.entry_barriers, ' · '), 'evidence', 'verified'); end if;
  if p_brand.industry is not null then
    select n.note into v_note from public.lab_market_category_notes n where n.market_code = m.code and n.industry = p_brand.industry;
    if v_note is not null then
      considerations := considerations || jsonb_build_object('label', 'For ' || public.lab_label(p_brand.industry), 'text', v_note, 'evidence', 'verified');
    end if;
  end if;
  if m.confidence = 'unverified' then steps := steps || to_jsonb('This market profile holds basic facts only; validate demand with a small test before committing budget.'::text); end if;
  if m.outdated then steps := steps || to_jsonb('Parts of this profile are marked outdated by our team; treat them with care.'::text); end if;

  if scored >= 3 and p_result.id is not null then score := round(num / den, 1); end if;

  return jsonb_build_object(
    'code', m.code, 'name', m.name, 'status', case when score is null then 'insufficient' else 'scored' end,
    'score', score, 'factors', factors, 'considerations', considerations, 'missing', missing, 'next_steps', steps,
    'is_target', m.code = any (p_brand.target_markets),
    'profile', jsonb_build_object('confidence', m.confidence, 'last_verified_at', m.last_verified_at, 'outdated', m.outdated,
      'eu_member', m.eu_member, 'currency', m.currency, 'languages', to_jsonb(m.languages), 'overview', m.overview, 'consumer_notes', m.consumer_notes),
    'sources', (select coalesce(jsonb_agg(jsonb_build_object('title', s.title, 'url', s.url, 'publisher', s.publisher, 'accessed_on', s.accessed_on, 'field', s.field) order by s.field, s.title), '[]'::jsonb)
                from public.lab_market_sources s where s.market_code = m.code)
  );
end $$;

-- Compare up to three markets. Ranks them only when the evidence allows:
-- every market scored and the leader ahead by at least five points.
create or replace function public.lab_market_fit(p_brand uuid, p_codes text[])
returns jsonb language plpgsql security definer set search_path = public as $$
declare b public.lab_brands; r public.lab_results; items jsonb := '[]'::jsonb; c text; ranked jsonb; reason text; possible boolean := false; scores numeric[];
begin
  perform public.lab_require_member(p_brand);
  if array_length(p_codes, 1) is null or array_length(p_codes, 1) > 3 then raise exception 'compare one to three markets' using errcode = '22023'; end if;
  select * into b from public.lab_brands where id = p_brand;
  select * into r from public.lab_results where brand_id = p_brand order by computed_at desc limit 1;
  foreach c in array array(select distinct upper(x) from unnest(p_codes) x) loop
    items := items || public.lab_market_fit_one(b, c, r);
  end loop;
  select jsonb_agg(x->>'code' order by (x->>'score')::numeric desc), array_agg((x->>'score')::numeric order by (x->>'score')::numeric desc)
    into ranked, scores from jsonb_array_elements(items) x where x->>'status' = 'scored';
  if jsonb_array_length(items) < 2 then
    reason := 'Add a second market to compare.';
  elsif exists (select 1 from jsonb_array_elements(items) x where x->>'status' <> 'scored') then
    reason := 'Not every market can be scored yet, so we won''t rank them. See what''s missing under each.';
  elsif scores[1] - scores[2] < 5 then
    reason := 'The scores are within five points of each other: too close to call on this evidence.';
  else
    possible := true;
    reason := 'Ranked by market-fit score. The score reflects your readiness and our recorded data, not the size of the opportunity.';
  end if;
  insert into public.lab_events (kind, props) values ('markets_compared', jsonb_build_object('n', jsonb_array_length(items)));
  return jsonb_build_object('markets', items, 'ranking', jsonb_build_object('possible', possible, 'order', case when possible then ranked else '[]'::jsonb end, 'reason', reason),
    'readiness', case when r.id is null then null else jsonb_build_object('overall', r.overall, 'band', r.band_label, 'version', r.version, 'computed_at', r.computed_at) end);
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Matching
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_tier_rank(p text)
returns int language sql immutable as $$
  select case p when 'value' then 1 when 'mid' then 2 when 'premium' then 3 when 'luxury' then 4 end;
$$;

-- Evaluate one partner against one brand. Returns null when a hard filter
-- excludes the partner, otherwise the full, explained evaluation.
--   score    = Σ(weight × criterion) ÷ Σ(all weights) × 100
--              a criterion we can't evaluate (missing data) earns nothing:
--              missing information never counts in a partner's favour
--   coverage = share of the weights we could evaluate
create or replace function public.lab_match_one(p_brand public.lab_brands, p public.lab_partners, p_overall numeric, p_weights jsonb)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  cov text[]; need int; t public.lab_partner_types;
  crit jsonb := '[]'::jsonb; s numeric; w numeric; total numeric := 0; got numeric := 0; known numeric := 0;
  strong text[] := '{}'; weak text[] := '{}'; missing text[] := '{}'; reasons text[] := '{}'; limits text[] := '{}';
  brand_tags text[]; d int; expl text;
begin
  select * into t from public.lab_partner_types where key = p.type_key;
  cov := array(select market_code from public.lab_partner_markets where partner_id = p.id);
  if p.country_code is not null then cov := cov || p.country_code; end if;

  -- ── hard eligibility filters ──
  if p_brand.industry is not null and p_brand.industry = any (p.excluded_industries) then return null; end if;
  if array_length(p.accepts_offering, 1) is not null and not (p_brand.offering = any (p.accepts_offering)) then return null; end if;
  if array_length(p_brand.target_markets, 1) is not null and array_length(cov, 1) is not null
     and not (cov && (p_brand.target_markets || p_brand.current_markets)) then return null; end if;
  if p_brand.price_tier is not null and array_length(p.price_tiers, 1) is not null
     and (select min(abs(public.lab_tier_rank(x) - public.lab_tier_rank(p_brand.price_tier))) from unnest(p.price_tiers) x) >= 2 then return null; end if;
  if p.min_readiness is not null and p_overall is not null and p_overall < p.min_readiness - 20 then return null; end if;

  -- ── 1 · product category ──
  w := coalesce((p_weights->>'category')::numeric, 0); total := total + w;
  brand_tags := array(select lower(btrim(x)) from regexp_split_to_table(coalesce(p_brand.product_category, ''), '[,;/]') x where btrim(x) <> '');
  if array_length(p.industries, 1) is null and array_length(p.product_categories, 1) is null then
    s := null;
  else
    s := 0;
    if p_brand.industry is not null and p_brand.industry = any (p.industries) then s := 0.75; end if;
    if array_length(brand_tags, 1) is not null and brand_tags && array(select lower(x) from unnest(p.product_categories) x) then
      s := case when s > 0 then 1 else 0.6 end;
    end if;
  end if;
  crit := crit || jsonb_build_object('key', 'category', 'label', 'Product category', 'weight', w, 'score', s);

  -- ── 2 · geography ──
  w := coalesce((p_weights->>'geography')::numeric, 0); total := total + w;
  if array_length(p_brand.target_markets, 1) is null or array_length(cov, 1) is null then s := null;
  elsif cov && p_brand.target_markets then s := 1;
  elsif cov && p_brand.current_markets then s := 0.4;
  else s := 0; end if;
  crit := crit || jsonb_build_object('key', 'geography', 'label', 'Target geography', 'weight', w, 'score', s);

  -- ── 3 · price positioning ──
  w := coalesce((p_weights->>'price')::numeric, 0); total := total + w;
  if p_brand.price_tier is null or array_length(p.price_tiers, 1) is null then s := null;
  else
    d := (select min(abs(public.lab_tier_rank(x) - public.lab_tier_rank(p_brand.price_tier))) from unnest(p.price_tiers) x);
    s := case d when 0 then 1 when 1 then 0.5 else 0 end;
  end if;
  crit := crit || jsonb_build_object('key', 'price', 'label', 'Price positioning', 'weight', w, 'score', s);

  -- ── 4 · customer segment ──
  w := coalesce((p_weights->>'segment')::numeric, 0); total := total + w;
  if array_length(p_brand.customer_segments, 1) is null or array_length(p.customer_segments, 1) is null then s := null;
  else
    s := (select count(*) from unnest(p_brand.customer_segments) x where x = any (p.customer_segments))::numeric
         / least(array_length(p_brand.customer_segments, 1), array_length(p.customer_segments, 1));
    if s = 0 and ('broad' = any (p_brand.customer_segments) or 'broad' = any (p.customer_segments)) then s := 0.5; end if;
    s := least(1, s);
  end if;
  crit := crit || jsonb_build_object('key', 'segment', 'label', 'Customer segment', 'weight', w, 'score', round(s, 2));

  -- ── 5 · distribution model ──
  w := coalesce((p_weights->>'distribution')::numeric, 0); total := total + w;
  if p_brand.distribution_model is null or array_length(p.distribution_models, 1) is null then s := null;
  elsif p_brand.distribution_model = 'undecided' then s := 0.5;
  elsif p_brand.distribution_model = any (p.distribution_models) then s := 1;
  elsif p_brand.distribution_model = 'hybrid' or 'hybrid' = any (p.distribution_models) then s := 0.75;
  else s := 0.2; end if;
  crit := crit || jsonb_build_object('key', 'distribution', 'label', 'Distribution model', 'weight', w, 'score', s);

  -- ── 6 · commercial readiness ──
  w := coalesce((p_weights->>'readiness')::numeric, 0); total := total + w;
  need := coalesce(p.min_readiness, t.expected_readiness, 40);
  if p_overall is null then s := null;
  elsif need <= 0 then s := 1;
  else s := round(least(1, p_overall / need), 2); end if;
  crit := crit || jsonb_build_object('key', 'readiness', 'label', 'Commercial readiness', 'weight', w, 'score', s, 'needs', need);

  -- ── combine and explain ──
  for s, w, expl in select (x->>'score')::numeric, (x->>'weight')::numeric, x->>'key' from jsonb_array_elements(crit) x loop
    if s is null then
      missing := missing || expl;
    else
      known := known + w; got := got + w * s;
      if s >= 0.75 then strong := strong || expl; elsif s < 0.5 then weak := weak || expl; end if;
    end if;
  end loop;

  if array_length(strong, 1) is not null then
    reasons := reasons || (
      'Strong ' || array_to_string(array(select case k when 'category' then 'category' when 'geography' then 'geography' when 'segment' then 'customer' when 'distribution' then 'distribution' when 'readiness' then 'readiness' else null end
                                          from unnest(strong) k where k <> 'price'), ' and ') || ' alignment.');
    if 'price' = any (strong) then reasons := reasons || ('Your price positioning also fits this ' || lower(coalesce(t.label, 'partner')) || '''s recorded range.'); end if;
    reasons := array_remove(reasons, 'Strong  alignment.');
  end if;
  if 'category' = any (weak) then limits := limits || 'Category overlap is limited: check the partner''s current assortment.'::text; end if;
  if 'geography' = any (weak) then limits := limits || 'The partner works mainly outside your target markets.'::text; end if;
  if 'price' = any (weak) then limits := limits || 'Your price point sits outside the partner''s recorded range.'::text; end if;
  if 'segment' = any (weak) then limits := limits || 'Your customer and theirs overlap only partly.'::text; end if;
  if 'distribution' = any (weak) then limits := limits || 'Your preferred distribution model differs from how this partner works.'::text; end if;
  if 'readiness' = any (weak) then limits := limits || ('Partners like this usually expect a readiness of about ' || need || '.')::text; end if;
  if p_brand.distribution_model = 'undecided' then limits := limits || 'You haven''t chosen a distribution model yet.'::text; end if;
  if p.verification_status = 'research_prospect' then limits := limits || 'A research prospect: we have not verified this organisation''s details yet.'::text; end if;
  if array_length(missing, 1) is not null then
    expl := array_to_string(array(select case k when 'category' then 'category fit' when 'geography' then 'geographic coverage' when 'price' then 'price range'
                                             when 'segment' then 'customer profile' when 'distribution' then 'distribution requirements' when 'readiness' then 'readiness expectations' end
                                      from unnest(missing) k), ', ');
    reasons := reasons || (upper(left(expl, 1)) || substr(expl, 2) || case when array_length(missing, 1) = 1 then ' still needs' else ' still need' end || ' verification.');
  end if;

  return jsonb_build_object(
    'score', case when total > 0 then round(100 * got / total)::int else 0 end,
    'coverage', case when total > 0 then round(100 * known / total)::int else 0 end,
    'criteria', crit, 'reasons', to_jsonb(reasons), 'limitations', to_jsonb(limits), 'missing', to_jsonb(missing)
  );
end $$;

-- Public face of a partner: what a brand may see. Never contacts, never
-- internal notes, never the raw matching attributes beyond what explains a match.
create or replace function public.lab_partner_public(p public.lab_partners)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'id', p.id, 'name', p.name, 'website', p.website, 'country_code', p.country_code, 'city', p.city,
    'type_key', p.type_key, 'type_label', (select label from public.lab_partner_types where key = p.type_key),
    'description', p.description, 'industries', to_jsonb(p.industries), 'product_categories', to_jsonb(p.product_categories),
    'price_tiers', to_jsonb(p.price_tiers), 'distribution_models', to_jsonb(p.distribution_models),
    'brand_requirements', p.brand_requirements, 'business_size', p.business_size,
    'coverage', (select coalesce(jsonb_agg(market_code order by market_code), '[]'::jsonb) from public.lab_partner_markets where partner_id = p.id),
    'verification_status', p.verification_status, 'last_verified_at', p.last_verified_at, 'source_url', p.source_url,
    'accepts_introductions', p.accepts_introductions, 'is_fixture', p.is_fixture
  );
$$;

-- Generate matches for a brand. p_filters (all optional): country, city,
-- type, industry, price_tier, verification, min_score.
create or replace function public.lab_run_matching(p_brand uuid, p_filters jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  b public.lab_brands; r public.lab_results; cfg public.lab_matching_configs; st public.lab_settings;
  p public.lab_partners; ev jsonb; v_run uuid; eligible int := 0; excluded int := 0; recent int;
  f jsonb := coalesce(p_filters, '{}'::jsonb);
begin
  perform public.lab_require_member(p_brand);
  select * into st from public.lab_settings where id = 1;
  select count(*) into recent from public.lab_match_runs where brand_id = p_brand and created_at > now() - interval '1 hour';
  if recent >= st.match_runs_per_hour and not public.lab_is_admin() then
    raise exception 'too many match runs in the last hour; try again shortly' using errcode = '54000';
  end if;
  select * into b from public.lab_brands where id = p_brand;
  select * into r from public.lab_results where brand_id = p_brand order by computed_at desc limit 1;
  select * into cfg from public.lab_matching_configs where active;
  if cfg.id is null then raise exception 'matching is not configured' using errcode = '22023'; end if;

  insert into public.lab_match_runs (brand_id, config_id, result_id, filters, created_by)
  values (p_brand, cfg.id, r.id, f, auth.uid()) returning id into v_run;

  for p in select * from public.lab_partners x where public.lab_partner_visible(x) order by x.name loop
    if f ? 'country' and coalesce(f->>'country', '') <> '' and p.country_code is distinct from upper(f->>'country')
       and not exists (select 1 from public.lab_partner_markets pm where pm.partner_id = p.id and pm.market_code = upper(f->>'country')) then continue; end if;
    if f ? 'city' and coalesce(f->>'city', '') <> '' and lower(coalesce(p.city, '')) <> lower(f->>'city') then continue; end if;
    if f ? 'type' and coalesce(f->>'type', '') <> '' and p.type_key <> f->>'type' then continue; end if;
    if f ? 'industry' and coalesce(f->>'industry', '') <> '' and not ((f->>'industry') = any (p.industries)) then continue; end if;
    if f ? 'price_tier' and coalesce(f->>'price_tier', '') <> '' and not ((f->>'price_tier') = any (p.price_tiers)) then continue; end if;
    if f ? 'verification' and coalesce(f->>'verification', '') <> '' and p.verification_status <> f->>'verification' then continue; end if;
    ev := public.lab_match_one(b, p, r.overall, cfg.weights);
    if ev is null then excluded := excluded + 1; continue; end if;
    if f ? 'min_score' and (ev->>'score')::int < coalesce((f->>'min_score')::int, 0) then continue; end if;
    eligible := eligible + 1;
    insert into public.lab_matches (run_id, brand_id, partner_id, score, coverage, rank, criteria, reasons, limitations, missing)
    values (v_run, p_brand, p.id, (ev->>'score')::int, (ev->>'coverage')::int, 0, ev->'criteria',
            array(select jsonb_array_elements_text(ev->'reasons')), array(select jsonb_array_elements_text(ev->'limitations')),
            array(select jsonb_array_elements_text(ev->'missing')));
  end loop;

  update public.lab_matches m set rank = x.rn
  from (select mm.id, row_number() over (order by mm.score desc, mm.coverage desc, pp.name) rn
        from public.lab_matches mm join public.lab_partners pp on pp.id = mm.partner_id where mm.run_id = v_run) x
  where m.id = x.id;
  update public.lab_match_runs set eligible_count = eligible, excluded_count = excluded where id = v_run;
  insert into public.lab_events (kind, props) values ('match_viewed', jsonb_build_object('n', eligible));
  return public.lab_match_results(v_run);
end $$;

create or replace function public.lab_match_results(p_run uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare run public.lab_match_runs; cfg public.lab_matching_configs;
begin
  select * into run from public.lab_match_runs where id = p_run;
  if run.id is null then raise exception 'match run not found' using errcode = '22023'; end if;
  perform public.lab_require_member(run.brand_id);
  select * into cfg from public.lab_matching_configs where id = run.config_id;
  return jsonb_build_object(
    'run', jsonb_build_object('id', run.id, 'created_at', run.created_at, 'filters', run.filters, 'eligible', run.eligible_count, 'excluded', run.excluded_count,
                              'config_version', cfg.version, 'weights', cfg.weights, 'min_score', cfg.min_score, 'used_result', run.result_id),
    'matches', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'partner', public.lab_partner_public(p), 'score', m.score, 'coverage', m.coverage, 'rank', m.rank, 'criteria', m.criteria,
        'reasons', to_jsonb(m.reasons), 'limitations', to_jsonb(m.limitations), 'missing', to_jsonb(m.missing),
        'saved', exists (select 1 from public.lab_saved_matches s where s.brand_id = m.brand_id and s.partner_id = m.partner_id),
        'introduction', (select jsonb_build_object('id', i.id, 'status', i.status) from public.lab_introductions i
                         where i.brand_id = m.brand_id and i.partner_id = m.partner_id order by i.created_at desc limit 1)
      ) order by m.rank), '[]'::jsonb)
      from public.lab_matches m join public.lab_partners p on p.id = m.partner_id
      where m.run_id = run.id and public.lab_partner_visible(p)
    )
  );
end $$;

create or replace function public.lab_latest_matches(p_brand uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_run uuid;
begin
  perform public.lab_require_member(p_brand);
  select id into v_run from public.lab_match_runs where brand_id = p_brand order by created_at desc limit 1;
  if v_run is null then return null; end if;
  return public.lab_match_results(v_run);
end $$;

create or replace function public.lab_partner_profile(p_partner uuid, p_brand uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare p public.lab_partners;
begin
  perform public.lab_require_member(p_brand);
  select * into p from public.lab_partners where id = p_partner;
  if p.id is null or not public.lab_partner_visible(p) then raise exception 'partner not available' using errcode = '22023'; end if;
  return jsonb_build_object(
    'partner', public.lab_partner_public(p),
    'match', (select jsonb_build_object('score', m.score, 'coverage', m.coverage, 'criteria', m.criteria, 'reasons', to_jsonb(m.reasons), 'limitations', to_jsonb(m.limitations), 'missing', to_jsonb(m.missing), 'computed_at', m.created_at)
              from public.lab_matches m where m.brand_id = p_brand and m.partner_id = p.id order by m.created_at desc limit 1),
    'saved', (select jsonb_build_object('note', s.note, 'created_at', s.created_at) from public.lab_saved_matches s where s.brand_id = p_brand and s.partner_id = p.id),
    'introductions', (select coalesce(jsonb_agg(jsonb_build_object('id', i.id, 'status', i.status, 'purpose', i.purpose, 'created_at', i.created_at) order by i.created_at desc), '[]'::jsonb)
                      from public.lab_introductions i where i.brand_id = p_brand and i.partner_id = p.id)
  );
end $$;

create or replace function public.lab_saved_list(p_brand uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  perform public.lab_require_member(p_brand);
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
      'partner', public.lab_partner_public(p), 'note', s.note, 'saved_at', s.created_at,
      'score', (select m.score from public.lab_matches m where m.brand_id = s.brand_id and m.partner_id = s.partner_id order by m.created_at desc limit 1),
      'introduction', (select jsonb_build_object('id', i.id, 'status', i.status) from public.lab_introductions i where i.brand_id = s.brand_id and i.partner_id = s.partner_id order by i.created_at desc limit 1)
    ) order by s.created_at desc), '[]'::jsonb)
    from public.lab_saved_matches s join public.lab_partners p on p.id = s.partner_id
    where s.brand_id = p_brand and public.lab_partner_visible(p)
  );
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Introductions and research requests
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_request_introduction(p_brand uuid, p_partner uuid, p_purpose text, p_message text)
returns uuid language plpgsql security definer set search_path = public as $$
declare p public.lab_partners; v_id uuid; n int; lim int; bname text;
begin
  perform public.lab_require_member(p_brand);
  select * into p from public.lab_partners where id = p_partner;
  if p.id is null or not public.lab_partner_visible(p) then raise exception 'partner not available' using errcode = '22023'; end if;
  if p_purpose is null or p_purpose not in ('retail_listing', 'distribution', 'wholesale', 'market_entry_support', 'collaboration', 'service', 'other') then
    raise exception 'choose what the introduction is for' using errcode = '22023';
  end if;
  if char_length(coalesce(p_message, '')) > 1500 then raise exception 'message is too long' using errcode = '22023'; end if;
  select intro_daily_limit into lim from public.lab_settings where id = 1;
  select count(*) into n from public.lab_introductions where brand_id = p_brand and created_at > now() - interval '1 day';
  if n >= lim then raise exception 'daily request limit reached; try again tomorrow' using errcode = '54000'; end if;
  if exists (select 1 from public.lab_introductions where brand_id = p_brand and partner_id = p_partner and status not in ('declined', 'completed', 'closed')) then
    raise exception 'there is already an open request for this partner' using errcode = '23505';
  end if;
  insert into public.lab_introductions (brand_id, partner_id, requested_by, purpose, message)
  values (p_brand, p_partner, auth.uid(), p_purpose, nullif(btrim(coalesce(p_message, '')), '')) returning id into v_id;
  insert into public.lab_introduction_events (introduction_id, status, note, actor_id, actor_role) values (v_id, 'requested', null, auth.uid(), 'user');
  select name into bname from public.lab_brands where id = p_brand;
  perform public.lab_notify(null, p_brand, 'intro_requested', 'Introduction request: ' || bname || ' → ' || p.name, p_purpose, '/admin/lab/introductions?id=' || v_id);
  return v_id;
end $$;

create or replace function public.lab_request_research(p_brand uuid, p_markets text[], p_types text[], p_message text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; n int; lim int; bname text;
begin
  perform public.lab_require_member(p_brand);
  if char_length(coalesce(p_message, '')) > 1500 then raise exception 'message is too long' using errcode = '22023'; end if;
  if exists (select 1 from unnest(coalesce(p_markets, '{}')) m where m !~ '^[A-Z]{2}$') then raise exception 'invalid market code' using errcode = '22023'; end if;
  select intro_daily_limit into lim from public.lab_settings where id = 1;
  select count(*) into n from public.lab_introductions where brand_id = p_brand and created_at > now() - interval '1 day';
  if n >= lim then raise exception 'daily request limit reached; try again tomorrow' using errcode = '54000'; end if;
  insert into public.lab_introductions (brand_id, partner_id, requested_by, purpose, message, market_codes, partner_types)
  values (p_brand, null, auth.uid(), 'research', nullif(btrim(coalesce(p_message, '')), ''), coalesce(p_markets, '{}'),
          array(select t from unnest(coalesce(p_types, '{}')) t where exists (select 1 from public.lab_partner_types where key = t)))
  returning id into v_id;
  insert into public.lab_introduction_events (introduction_id, status, actor_id, actor_role) values (v_id, 'requested', auth.uid(), 'user');
  select name into bname from public.lab_brands where id = p_brand;
  perform public.lab_notify(null, p_brand, 'research_requested', 'Research request: ' || bname, array_to_string(coalesce(p_markets, '{}'), ', '), '/admin/lab/introductions?id=' || v_id);
  return v_id;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Reports
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_generate_report(p_brand uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  b public.lab_brands; r public.lab_results; v_id uuid; snap jsonb; n int; lim int; cfg public.lab_matching_configs;
  recs jsonb; cats jsonb; markets jsonb; band jsonb;
begin
  perform public.lab_require_member(p_brand);
  select reports_per_day into lim from public.lab_settings where id = 1;
  select count(*) into n from public.lab_reports where brand_id = p_brand and created_at > now() - interval '1 day';
  if n >= lim then raise exception 'daily report limit reached' using errcode = '54000'; end if;
  select * into b from public.lab_brands where id = p_brand;
  select * into r from public.lab_results where brand_id = p_brand order by computed_at desc limit 1;
  if r.id is null then raise exception 'complete an assessment before generating a report' using errcode = '22023'; end if;
  select * into cfg from public.lab_matching_configs where active;

  select coalesce(jsonb_agg(jsonb_build_object('key', key, 'score', (value->>'score')::numeric, 'weight', value->'weight') order by (value->>'score')::numeric desc nulls last), '[]'::jsonb)
    into cats from jsonb_each(r.categories);
  select coalesce(jsonb_agg(jsonb_build_object('key', rule_key, 'title', title, 'body', body, 'category', category, 'priority', priority, 'partner_types', to_jsonb(partner_types)) order by priority desc), '[]'::jsonb)
    into recs from public.lab_result_recommendations where result_id = r.id;
  select b2 into band from jsonb_array_elements(r.bands) b2 where b2->>'key' = r.band_key;
  if array_length(b.target_markets, 1) is not null then
    markets := public.lab_market_fit(p_brand, b.target_markets[1:3]);
  end if;

  snap := jsonb_build_object(
    'generated_at', now(),
    'brand', jsonb_build_object('name', b.name, 'website', b.website, 'origin_country', b.origin_country, 'industry', b.industry, 'product_category', b.product_category,
      'offering', b.offering, 'description', b.description, 'price_tier', b.price_tier, 'typical_price_eur', b.typical_price_eur,
      'sales_channels', to_jsonb(b.sales_channels), 'current_markets', to_jsonb(b.current_markets), 'sales_stage', b.sales_stage, 'customer_segments', to_jsonb(b.customer_segments)),
    'objectives', jsonb_build_object('target_markets', to_jsonb(b.target_markets), 'entry_timeline', b.entry_timeline, 'primary_objective', b.primary_objective,
      'distribution_model', b.distribution_model, 'budget_range', b.budget_range, 'obstacles', to_jsonb(b.obstacles)),
    'readiness', jsonb_build_object('overall', r.overall, 'band_key', r.band_key, 'band_label', r.band_label, 'band_summary', band->>'summary',
      'version', r.version, 'computed_at', r.computed_at, 'categories', cats, 'answered', r.answered, 'applicable', r.applicable),
    'strengths', (select coalesce(jsonb_agg(x), '[]'::jsonb) from (select x from jsonb_array_elements(cats) x where (x->>'score')::numeric >= 70 limit 3) s),
    'risks', (select coalesce(jsonb_agg(x order by (x->>'score')::numeric), '[]'::jsonb) from jsonb_array_elements(cats) x where (x->>'score')::numeric < 50),
    'recommendations', recs,
    'markets', markets,
    'partner_types', (select coalesce(jsonb_agg(distinct jsonb_build_object('key', t.key, 'label', t.label)), '[]'::jsonb)
                      from public.lab_result_recommendations rr cross join lateral unnest(rr.partner_types) k join public.lab_partner_types t on t.key = k where rr.result_id = r.id),
    'saved_matches', public.lab_saved_list(p_brand),
    'introductions', (select coalesce(jsonb_agg(jsonb_build_object('partner', (select name from public.lab_partners where id = i.partner_id), 'purpose', i.purpose, 'status', i.status, 'created_at', i.created_at) order by i.created_at desc), '[]'::jsonb)
                      from public.lab_introductions i where i.brand_id = p_brand),
    'next_actions', (
      select coalesce(jsonb_agg(a), '[]'::jsonb) from (
        select jsonb_build_object('text', o.next_action, 'due', o.next_action_on, 'source', 'opportunity: ' || o.title) a
        from public.lab_opportunities o where o.brand_id = p_brand and o.next_action is not null and o.status not in ('won', 'lost')
        union all
        select jsonb_build_object('text', x->>'title', 'source', 'recommendation') from (select x from jsonb_array_elements(recs) x limit 3) y
      ) z
    ),
    'methodology', jsonb_build_object(
      'assessment_version', r.version, 'category_weights', r.weights, 'bands', r.bands,
      'matching_version', cfg.version, 'matching_weights', cfg.weights,
      'limitations', jsonb_build_array(
        'Readiness scores are product-defined readiness categories based on your own answers, not predictions of success.',
        'Market-fit scores combine your answers with the facts recorded in our market profiles; where a profile is unverified the score leans on your answers.',
        'Compatibility scores describe how well recorded attributes align. They do not mean a partner is interested or available.',
        'Recommendations are rule-based and drawn from your answers and scores.')
    )
  );
  insert into public.lab_reports (brand_id, result_id, title, snapshot, created_by)
  values (p_brand, r.id, b.name || ' · Expansion readiness · ' || to_char(now(), 'DD Mon YYYY'), snap, auth.uid()) returning id into v_id;
  return v_id;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Account: bootstrap, dashboard, analytics, export, deletion
-- ═════════════════════════════════════════════════════════════════════════

-- Called on every Lab sign-in. Staff who also use the Lab get a Lab profile
-- on first visit; nobody else's data is touched.
create or replace function public.lab_bootstrap()
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'sign in first' using errcode = '28000'; end if;
  insert into public.lab_profiles (user_id) values (auth.uid()) on conflict (user_id) do nothing;
  update public.lab_profiles set last_seen_at = now() where user_id = auth.uid();
  return jsonb_build_object(
    'profile', (select to_jsonb(p) from public.lab_profiles p where p.user_id = auth.uid()),
    'is_admin', public.lab_is_admin(),
    'brands', (select coalesce(jsonb_agg(jsonb_build_object('id', b.id, 'name', b.name, 'role', m.role) order by b.created_at), '[]'::jsonb)
               from public.lab_brand_members m join public.lab_brands b on b.id = m.brand_id where m.user_id = auth.uid()),
    'unread', (select count(*) from public.lab_notifications where user_id = auth.uid() and read_at is null)
  );
end $$;

create or replace function public.lab_dashboard(p_brand uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare r public.lab_results;
begin
  perform public.lab_require_member(p_brand);
  select * into r from public.lab_results where brand_id = p_brand order by computed_at desc limit 1;
  return jsonb_build_object(
    'brand', (select to_jsonb(b) from public.lab_brands b where b.id = p_brand),
    'latest_result', case when r.id is null then null else jsonb_build_object('id', r.id, 'overall', r.overall, 'band_label', r.band_label, 'version', r.version, 'computed_at', r.computed_at, 'categories', r.categories) end,
    'history', (select coalesce(jsonb_agg(jsonb_build_object('id', x.id, 'overall', x.overall, 'band_label', x.band_label, 'version', x.version, 'computed_at', x.computed_at) order by x.computed_at desc), '[]'::jsonb)
                from public.lab_results x where x.brand_id = p_brand),
    'open_assessment', (select jsonb_build_object('id', a.id, 'started_at', a.started_at, 'answered', (select count(*) from public.lab_responses where assessment_id = a.id))
                        from public.lab_assessments a where a.brand_id = p_brand and a.status = 'in_progress'),
    'priorities', (select coalesce(jsonb_agg(jsonb_build_object('title', rr.title, 'category', rr.category) order by rr.priority desc), '[]'::jsonb)
                   from (select * from public.lab_result_recommendations where result_id = r.id order by priority desc limit 3) rr),
    'saved', (select count(*) from public.lab_saved_matches where brand_id = p_brand),
    'introductions', (select coalesce(jsonb_object_agg(status, n), '{}'::jsonb) from (select status, count(*) n from public.lab_introductions where brand_id = p_brand group by status) s),
    'opportunities', (select coalesce(jsonb_agg(jsonb_build_object('id', o.id, 'title', o.title, 'status', o.status, 'next_action', o.next_action, 'next_action_on', o.next_action_on) order by o.next_action_on nulls last, o.last_activity_at desc), '[]'::jsonb)
                      from (select * from public.lab_opportunities where brand_id = p_brand and status not in ('won', 'lost') limit 5) o),
    'reports', (select coalesce(jsonb_agg(jsonb_build_object('id', x.id, 'title', x.title, 'created_at', x.created_at) order by x.created_at desc), '[]'::jsonb)
                from (select * from public.lab_reports where brand_id = p_brand order by created_at desc limit 3) x),
    'notifications', (select coalesce(jsonb_agg(jsonb_build_object('id', n.id, 'title', n.title, 'body', n.body, 'link', n.link, 'created_at', n.created_at, 'read', n.read_at is not null) order by n.created_at desc), '[]'::jsonb)
                      from (select * from public.lab_notifications where user_id = auth.uid() and (brand_id = p_brand or brand_id is null) order by created_at desc limit 8) n)
  );
end $$;

-- Privacy-conscious analytics: an allow-listed event name and two small
-- properties at most. Callable before sign-in for the public preview.
create or replace function public.lab_track(p_kind text, p_props jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare clean jsonb := '{}'::jsonb; k text; v jsonb;
begin
  if p_kind not in ('preview_completed', 'report_downloaded', 'landing_cta') then return; end if;
  for k, v in select key, value from jsonb_each(coalesce(p_props, '{}'::jsonb)) limit 2 loop
    if k in ('band', 'cta', 'format') and jsonb_typeof(v) = 'string' and char_length(v #>> '{}') <= 40 then clean := clean || jsonb_build_object(k, v); end if;
  end loop;
  insert into public.lab_events (kind, props) values (p_kind, clean);
end $$;

create or replace function public.lab_export_my_data()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'sign in first' using errcode = '28000'; end if;
  return jsonb_build_object(
    'exported_at', now(),
    'account', (select jsonb_build_object('id', u.id, 'email', u.email, 'created_at', u.created_at) from auth.users u where u.id = uid),
    'profile', (select to_jsonb(p) from public.lab_profiles p where p.user_id = uid),
    'consents', (select coalesce(jsonb_agg(to_jsonb(c) order by c.created_at), '[]'::jsonb) from public.lab_consents c where c.user_id = uid),
    'brands', (select coalesce(jsonb_agg(jsonb_build_object(
        'brand', to_jsonb(b),
        'assessments', (select coalesce(jsonb_agg(jsonb_build_object('assessment', to_jsonb(a), 'answers', public.lab_answers_of(a.id))), '[]'::jsonb) from public.lab_assessments a where a.brand_id = b.id),
        'results', (select coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) from public.lab_results r where r.brand_id = b.id),
        'saved_matches', (select coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb) from public.lab_saved_matches s where s.brand_id = b.id),
        'introductions', (select coalesce(jsonb_agg(jsonb_build_object('request', to_jsonb(i), 'events', (select coalesce(jsonb_agg(to_jsonb(e)), '[]'::jsonb) from public.lab_introduction_events e where e.introduction_id = i.id))), '[]'::jsonb)
                          from public.lab_introductions i where i.brand_id = b.id),
        'opportunities', (select coalesce(jsonb_agg(jsonb_build_object('opportunity', to_jsonb(o), 'activity', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.lab_opportunity_activities x where x.opportunity_id = o.id and x.visible_to_user))), '[]'::jsonb)
                          from public.lab_opportunities o where o.brand_id = b.id),
        'reports', (select coalesce(jsonb_agg(jsonb_build_object('id', x.id, 'title', x.title, 'created_at', x.created_at, 'snapshot', x.snapshot)), '[]'::jsonb) from public.lab_reports x where x.brand_id = b.id)
      )), '[]'::jsonb)
      from public.lab_brands b where public.lab_is_member(b.id)),
    'notifications', (select coalesce(jsonb_agg(to_jsonb(n)), '[]'::jsonb) from public.lab_notifications n where n.user_id = uid)
  );
end $$;

-- Deletes the caller's Lab data and their login. Brands they own alone go
-- with them (assessments, results, matches, requests and reports cascade);
-- shared brands stay with the other owners. CMS staff accounts are removed
-- by an administrator instead, so nobody deletes the site's admin by accident.
create or replace function public.lab_delete_my_account()
returns void language plpgsql security definer set search_path = public, auth as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'sign in first' using errcode = '28000'; end if;
  if exists (select 1 from public.profiles where id = uid and role in ('admin', 'editor') and status = 'approved') then
    raise exception 'this is also a CMS staff account; ask an administrator to remove it' using errcode = '42501';
  end if;
  delete from public.lab_brands b
  where exists (select 1 from public.lab_brand_members m where m.brand_id = b.id and m.user_id = uid and m.role = 'owner')
    and not exists (select 1 from public.lab_brand_members m where m.brand_id = b.id and m.user_id <> uid and m.role = 'owner');
  delete from public.lab_brand_members where user_id = uid;
  insert into public.lab_audit (actor_id, action, entity, entity_id) values (null, 'account_deleted', 'user', md5(uid::text));
  delete from public.profiles where id = uid;
  delete from auth.users where id = uid;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Administration
-- ═════════════════════════════════════════════════════════════════════════

create or replace function public.lab_admin_stats(p_days int default 30)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare since timestamptz := now() - make_interval(days => greatest(1, least(p_days, 3650)));
  starts int; completes int;
begin
  perform public.lab_require_admin();
  select count(*), count(*) filter (where status = 'completed') into starts, completes from public.lab_assessments where started_at >= since;
  return jsonb_build_object(
    'since', since,
    'registrations', (select count(*) from public.lab_profiles where created_at >= since),
    'registrations_total', (select count(*) from public.lab_profiles),
    'brands', (select count(*) from public.lab_brands where created_at >= since),
    'brands_total', (select count(*) from public.lab_brands),
    'assessment_starts', starts,
    'assessment_completions', completes,
    'completion_rate', case when starts > 0 then round(100.0 * completes / starts) end,
    'top_markets', (select coalesce(jsonb_agg(jsonb_build_object('code', code, 'n', n) order by n desc, code), '[]'::jsonb)
                    from (select unnest(target_markets) code, count(*) n from public.lab_brands group by 1 order by 2 desc limit 9) t),
    'match_views', (select count(*) from public.lab_events where kind = 'match_viewed' and created_at >= since),
    'saved_matches', (select count(*) from public.lab_saved_matches where created_at >= since),
    'introduction_requests', (select count(*) from public.lab_introductions where created_at >= since and partner_id is not null),
    'research_requests', (select count(*) from public.lab_introductions where created_at >= since and partner_id is null),
    'open_requests', (select count(*) from public.lab_introductions where status in ('requested', 'under_review', 'more_info_needed')),
    'reports_generated', (select count(*) from public.lab_reports where created_at >= since),
    'report_downloads', (select count(*) from public.lab_events where kind = 'report_downloaded' and created_at >= since),
    'preview_completions', (select count(*) from public.lab_events where kind = 'preview_completed' and created_at >= since),
    'market_comparisons', (select count(*) from public.lab_events where kind = 'markets_compared' and created_at >= since)
  );
end $$;

create or replace function public.lab_admin_users()
returns jsonb language plpgsql stable security definer set search_path = public, auth as $$
begin
  perform public.lab_require_admin();
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
      'user_id', p.user_id, 'email', u.email, 'full_name', p.full_name, 'created_at', p.created_at, 'last_seen_at', p.last_seen_at,
      'confirmed', u.email_confirmed_at is not null,
      'brands', (select coalesce(jsonb_agg(jsonb_build_object('id', b.id, 'name', b.name,
                   'latest', (select jsonb_build_object('overall', r.overall, 'band', r.band_label) from public.lab_results r where r.brand_id = b.id order by r.computed_at desc limit 1),
                   'open_assessment', exists (select 1 from public.lab_assessments a where a.brand_id = b.id and a.status = 'in_progress'))), '[]'::jsonb)
                 from public.lab_brand_members m join public.lab_brands b on b.id = m.brand_id where m.user_id = p.user_id)
    ) order by p.created_at desc), '[]'::jsonb)
    from public.lab_profiles p join auth.users u on u.id = p.user_id
  );
end $$;

-- Copy a version (published or not) into a new draft for editing.
create or replace function public.lab_admin_clone_version(p_version uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare src public.lab_assessment_versions; v_new uuid; q record; v_q uuid;
begin
  perform public.lab_require_admin();
  select * into src from public.lab_assessment_versions where id = p_version;
  if src.id is null then raise exception 'version not found' using errcode = '22023'; end if;
  insert into public.lab_assessment_versions (version, title, status, category_weights, bands, notes)
  values ((select max(version) + 1 from public.lab_assessment_versions), src.title, 'draft', src.category_weights, src.bands, 'Copied from version ' || src.version)
  returning id into v_new;
  for q in select * from public.lab_questions where version_id = src.id loop
    insert into public.lab_questions (version_id, key, category, kind, prompt, help, why, weight, required, in_preview, applies_if, sort)
    values (v_new, q.key, q.category, q.kind, q.prompt, q.help, q.why, q.weight, q.required, q.in_preview, q.applies_if, q.sort) returning id into v_q;
    insert into public.lab_options (question_id, key, label, score, is_na, recommendation_key, sort)
    select v_q, key, label, score, is_na, recommendation_key, sort from public.lab_options where question_id = q.id;
  end loop;
  perform public.lab_log('clone', 'assessment_version', v_new::text, jsonb_build_object('from', src.version));
  return v_new;
end $$;

-- Check a draft and make it the live version. The previous one is archived;
-- results computed with it keep pointing at it.
create or replace function public.lab_admin_publish_version(p_version uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v public.lab_assessment_versions; total numeric; expected text[] := array['brand', 'pmf', 'commercial', 'operations', 'partnership', 'strategy'];
  b jsonb; prev numeric := -1; bad text;
begin
  perform public.lab_require_admin();
  select * into v from public.lab_assessment_versions where id = p_version for update;
  if v.id is null or v.status <> 'draft' then raise exception 'only drafts can be published' using errcode = '22023'; end if;
  if (select array_agg(k order by k) from jsonb_object_keys(v.category_weights) k) <> (select array_agg(x order by x) from unnest(expected) x) then
    raise exception 'weights must cover exactly: %', array_to_string(expected, ', ') using errcode = '22023';
  end if;
  select sum(value::numeric) into total from jsonb_each_text(v.category_weights);
  if abs(total - 100) > 0.5 then raise exception 'category weights add up to %, not 100', total using errcode = '22023'; end if;
  for b in select x from jsonb_array_elements(v.bands) x order by (x->>'min')::numeric loop
    if (b->>'min')::numeric <> prev + 1 then raise exception 'bands must run from 0 to 100 without gaps' using errcode = '22023'; end if;
    if coalesce(b->>'key', '') = '' or coalesce(b->>'label', '') = '' then raise exception 'every band needs a key and a label' using errcode = '22023'; end if;
    prev := (b->>'max')::numeric;
  end loop;
  if prev <> 100 then raise exception 'bands must end at 100' using errcode = '22023'; end if;
  select q.key into bad from public.lab_questions q where q.version_id = v.id and q.kind <> 'multi'
    and (select count(*) from public.lab_options o where o.question_id = q.id) < 2 limit 1;
  if bad is not null then raise exception 'question % needs at least two options', bad using errcode = '22023'; end if;
  if not exists (select 1 from public.lab_questions where version_id = v.id) then raise exception 'add questions first' using errcode = '22023'; end if;
  update public.lab_assessment_versions set status = 'archived' where status = 'published';
  update public.lab_assessment_versions set status = 'published', published_at = now() where id = v.id;
  perform public.lab_log('publish', 'assessment_version', v.id::text, jsonb_build_object('version', v.version));
end $$;

-- Score arbitrary answers against any version: the admin "preview before
-- publishing" tool. Writes nothing.
create or replace function public.lab_admin_preview_score(p_version uuid, p_brand jsonb, p_answers jsonb)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare s jsonb;
begin
  perform public.lab_require_admin();
  s := public.lab_score_core(p_version, coalesce(p_brand, '{}'::jsonb), p_answers);
  return s || jsonb_build_object('recommendations', public.lab_recommend(s, coalesce(p_brand, '{}'::jsonb)));
end $$;

create or replace function public.lab_admin_set_matching(p_weights jsonb, p_min_score int, p_notes text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare total numeric; v_id uuid; expected text[] := array['category', 'distribution', 'geography', 'price', 'readiness', 'segment'];
begin
  perform public.lab_require_admin();
  if (select array_agg(k order by k) from jsonb_object_keys(p_weights) k) <> expected then
    raise exception 'weights must cover exactly: %', array_to_string(expected, ', ') using errcode = '22023';
  end if;
  if exists (select 1 from jsonb_each_text(p_weights) where value::numeric < 0) then raise exception 'weights cannot be negative' using errcode = '22023'; end if;
  select sum(value::numeric) into total from jsonb_each_text(p_weights);
  if abs(total - 100) > 0.5 then raise exception 'matching weights add up to %, not 100', total using errcode = '22023'; end if;
  update public.lab_matching_configs set active = false where active;
  insert into public.lab_matching_configs (version, weights, min_score, active, notes, created_by)
  values ((select coalesce(max(version), 0) + 1 from public.lab_matching_configs), p_weights, greatest(0, least(100, coalesce(p_min_score, 40))), true, p_notes, auth.uid())
  returning id into v_id;
  perform public.lab_log('set_weights', 'matching_config', v_id::text, p_weights);
  return v_id;
end $$;

-- Move an introduction forward. p_note is shown to the brand; p_internal
-- stays in lab_introduction_notes, which no brand can read.
create or replace function public.lab_admin_update_introduction(p_id uuid, p_status text, p_note text default null, p_internal text default null)
returns void language plpgsql security definer set search_path = public as $$
declare i public.lab_introductions; pname text; m record; v_opp uuid;
begin
  perform public.lab_require_admin();
  select * into i from public.lab_introductions where id = p_id for update;
  if i.id is null then raise exception 'request not found' using errcode = '22023'; end if;
  if p_status not in ('requested', 'under_review', 'more_info_needed', 'approved', 'declined', 'introduction_sent', 'in_discussion', 'completed', 'closed') then
    raise exception 'unknown status %', p_status using errcode = '22023';
  end if;
  update public.lab_introductions set status = p_status where id = i.id;
  if p_status <> i.status or nullif(btrim(coalesce(p_note, '')), '') is not null then
    insert into public.lab_introduction_events (introduction_id, status, note, actor_id, actor_role)
    values (i.id, p_status, nullif(btrim(coalesce(p_note, '')), ''), auth.uid(), 'staff');
  end if;
  if nullif(btrim(coalesce(p_internal, '')), '') is not null then
    insert into public.lab_introduction_notes (introduction_id, body, author_id) values (i.id, btrim(p_internal), auth.uid());
  end if;
  select name into pname from public.lab_partners where id = i.partner_id;
  -- an introduction that has happened becomes an opportunity in the brand's pipeline
  if p_status in ('introduction_sent', 'in_discussion') and i.partner_id is not null and not exists (select 1 from public.lab_opportunities where introduction_id = i.id) then
    insert into public.lab_opportunities (brand_id, partner_id, introduction_id, kind, title, status, created_by)
    values (i.brand_id, i.partner_id, i.id,
            case i.purpose when 'retail_listing' then 'retail' when 'distribution' then 'distribution' when 'wholesale' then 'wholesale'
                           when 'collaboration' then 'collaboration' when 'market_entry_support' then 'market_entry' else 'other' end,
            'Introduction: ' || coalesce(pname, 'partner'), case when p_status = 'in_discussion' then 'in_discussion' else 'exploring' end, auth.uid())
    returning id into v_opp;
    insert into public.lab_opportunity_activities (opportunity_id, kind, body, actor_id) values (v_opp, 'system', 'Created from your introduction request.', auth.uid());
  end if;
  for m in select user_id from public.lab_brand_members where brand_id = i.brand_id loop
    perform public.lab_notify(m.user_id, i.brand_id, 'intro_status',
      case when i.partner_id is null then 'Research request: ' else 'Introduction to ' || coalesce(pname, 'partner') || ': ' end || replace(p_status, '_', ' '),
      nullif(btrim(coalesce(p_note, '')), ''), '/lab/matches?tab=requests');
  end loop;
  perform public.lab_log('status', 'introduction', i.id::text, jsonb_build_object('from', i.status, 'to', p_status));
end $$;

-- Bulk import from CSV (parsed in the admin, validated here). Deduplicates
-- on website domain, then on name + country. New records arrive unlisted
-- research prospects unless the file says otherwise. p_dry_run reports
-- what would happen without writing.
create or replace function public.lab_admin_import_partners(p_rows jsonb, p_dry_run boolean default true)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  r jsonb; i int := 0; inserted int := 0; updated int := 0; skipped int := 0; errors jsonb := '[]'::jsonb;
  v_id uuid; dom text; nm text; cc text; tk text; web text; arr_err text; markets text[]; seen text[] := '{}'; key text;
begin
  perform public.lab_require_admin();
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'rows must be an array' using errcode = '22023'; end if;
  if jsonb_array_length(p_rows) > 2000 then raise exception 'import at most 2000 rows at a time' using errcode = '22023'; end if;
  for r in select value from jsonb_array_elements(p_rows) loop
    i := i + 1;
    nm := btrim(coalesce(r->>'name', ''));
    cc := upper(nullif(btrim(coalesce(r->>'country_code', '')), ''));
    tk := lower(nullif(btrim(coalesce(r->>'type_key', '')), ''));
    web := nullif(btrim(coalesce(r->>'website', '')), '');
    if nm = '' then errors := errors || jsonb_build_object('row', i, 'error', 'name is required'); skipped := skipped + 1; continue; end if;
    if tk is null or not exists (select 1 from public.lab_partner_types where key = tk) then errors := errors || jsonb_build_object('row', i, 'error', 'unknown type_key ' || coalesce(tk, '(empty)')); skipped := skipped + 1; continue; end if;
    if cc is not null and cc !~ '^[A-Z]{2}$' then errors := errors || jsonb_build_object('row', i, 'error', 'country_code must be two letters'); skipped := skipped + 1; continue; end if;
    if web is not null and web !~* '^https?://[^\s]+$' then errors := errors || jsonb_build_object('row', i, 'error', 'website must start with http:// or https://'); skipped := skipped + 1; continue; end if;
    markets := array(select upper(btrim(x)) from jsonb_array_elements_text(coalesce(r->'markets', '[]'::jsonb)) x where btrim(x) <> '');
    if exists (select 1 from unnest(markets) m where m !~ '^[A-Z]{2}$') then errors := errors || jsonb_build_object('row', i, 'error', 'markets must be two-letter codes'); skipped := skipped + 1; continue; end if;
    dom := lower(regexp_replace(regexp_replace(coalesce(web, ''), '^https?://(www\.)?', '', 'i'), '/.*$', ''));
    key := coalesce(nullif(dom, ''), lower(nm) || '|' || coalesce(cc, ''));
    if key = any (seen) then errors := errors || jsonb_build_object('row', i, 'error', 'duplicate of an earlier row in this file'); skipped := skipped + 1; continue; end if;
    seen := seen || key;
    select id into v_id from public.lab_partners where not archived and ((dom <> '' and website_domain = dom) or (lower(name) = lower(nm) and country_code is not distinct from cc)) limit 1;
    if p_dry_run then
      if v_id is null then inserted := inserted + 1; else updated := updated + 1; end if;
      continue;
    end if;
    begin
      if v_id is null then
        insert into public.lab_partners (name, website, country_code, city, type_key, description, industries, product_categories, customer_segments, price_tiers,
          distribution_models, accepts_offering, brand_requirements, business_size, min_readiness, source_url, last_verified_at, verification_status, listed, updated_by)
        values (nm, web, cc, nullif(btrim(coalesce(r->>'city', '')), ''), tk, nullif(r->>'description', ''),
          array(select jsonb_array_elements_text(coalesce(r->'industries', '[]'::jsonb))),
          array(select jsonb_array_elements_text(coalesce(r->'product_categories', '[]'::jsonb))),
          array(select jsonb_array_elements_text(coalesce(r->'customer_segments', '[]'::jsonb))),
          array(select jsonb_array_elements_text(coalesce(r->'price_tiers', '[]'::jsonb))),
          array(select jsonb_array_elements_text(coalesce(r->'distribution_models', '[]'::jsonb))),
          array(select jsonb_array_elements_text(coalesce(r->'accepts_offering', '[]'::jsonb))),
          nullif(r->>'brand_requirements', ''), nullif(r->>'business_size', ''), nullif(r->>'min_readiness', '')::int,
          nullif(r->>'source_url', ''), nullif(r->>'last_verified_at', '')::date,
          coalesce(nullif(r->>'verification_status', ''), 'research_prospect'), coalesce((r->>'listed')::boolean, false), auth.uid())
        returning id into v_id;
        inserted := inserted + 1;
      else
        update public.lab_partners set
          website = coalesce(web, website), city = coalesce(nullif(btrim(coalesce(r->>'city', '')), ''), city), type_key = tk,
          description = coalesce(nullif(r->>'description', ''), description),
          industries = case when r ? 'industries' then array(select jsonb_array_elements_text(r->'industries')) else industries end,
          product_categories = case when r ? 'product_categories' then array(select jsonb_array_elements_text(r->'product_categories')) else product_categories end,
          customer_segments = case when r ? 'customer_segments' then array(select jsonb_array_elements_text(r->'customer_segments')) else customer_segments end,
          price_tiers = case when r ? 'price_tiers' then array(select jsonb_array_elements_text(r->'price_tiers')) else price_tiers end,
          distribution_models = case when r ? 'distribution_models' then array(select jsonb_array_elements_text(r->'distribution_models')) else distribution_models end,
          source_url = coalesce(nullif(r->>'source_url', ''), source_url),
          last_verified_at = coalesce(nullif(r->>'last_verified_at', '')::date, last_verified_at),
          verification_status = coalesce(nullif(r->>'verification_status', ''), verification_status),
          updated_by = auth.uid()
        where id = v_id;
        updated := updated + 1;
      end if;
      if array_length(markets, 1) is not null then
        delete from public.lab_partner_markets where partner_id = v_id;
        insert into public.lab_partner_markets (partner_id, market_code) select v_id, m from unnest(markets) m on conflict do nothing;
      end if;
    exception when others then
      errors := errors || jsonb_build_object('row', i, 'error', sqlerrm);
      skipped := skipped + 1;
    end;
  end loop;
  if not p_dry_run then perform public.lab_log('import', 'partners', null, jsonb_build_object('inserted', inserted, 'updated', updated, 'skipped', skipped)); end if;
  return jsonb_build_object('dry_run', p_dry_run, 'rows', i, 'inserted', inserted, 'updated', updated, 'skipped', skipped, 'errors', errors);
end $$;

-- Audit trail for configuration and partner changes (columns, not values).
create or replace function public.lab_audit_trigger()
returns trigger language plpgsql security definer set search_path = public as $$
declare changed text[];
begin
  if tg_op = 'UPDATE' then
    select array_agg(n.key) into changed from jsonb_each(to_jsonb(new)) n where n.value is distinct from (to_jsonb(old) -> n.key) and n.key not in ('updated_at', 'updated_by');
    if changed is null then return new; end if;
  end if;
  insert into public.lab_audit (actor_id, action, entity, entity_id, detail)
  values (auth.uid(), lower(tg_op), tg_table_name, coalesce(to_jsonb(new) ->> 'id', to_jsonb(new) ->> 'code', to_jsonb(old) ->> 'id', to_jsonb(old) ->> 'code'),
          case when changed is not null then jsonb_build_object('columns', to_jsonb(changed)) end);
  return coalesce(new, old);
end $$;
do $$ declare t text; begin
  foreach t in array array['lab_partners', 'lab_markets', 'lab_settings', 'lab_recommendation_rules', 'lab_partner_types', 'lab_partner_contacts'] loop
    execute format('drop trigger if exists %1$s_audit on public.%1$s', t);
    execute format('create trigger %1$s_audit after insert or update or delete on public.%1$s for each row execute function public.lab_audit_trigger()', t);
  end loop;
end $$;

-- ═════════════════════════════════════════════════════════════════════════
-- Execution rights: nothing is callable by default
-- ═════════════════════════════════════════════════════════════════════════
do $$ declare f record; begin
  for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname like 'lab\_%' loop
    execute format('revoke execute on function %s from public, anon, authenticated', f.sig);
  end loop;
end $$;
-- helpers RLS and triggers need
grant execute on function public.lab_is_member(uuid), public.lab_is_admin(), public.lab_fixtures_visible(), public.lab_partner_visible(public.lab_partners) to anon, authenticated;
-- user-facing API
grant execute on function
  public.lab_bootstrap(), public.lab_dashboard(uuid),
  public.lab_start_assessment(uuid, boolean), public.lab_assessment_state(uuid), public.lab_save_answer(uuid, text, text[]), public.lab_complete_assessment(uuid),
  public.lab_market_fit(uuid, text[]),
  public.lab_run_matching(uuid, jsonb), public.lab_match_results(uuid), public.lab_latest_matches(uuid), public.lab_partner_profile(uuid, uuid), public.lab_saved_list(uuid),
  public.lab_request_introduction(uuid, uuid, text, text), public.lab_request_research(uuid, text[], text[], text),
  public.lab_generate_report(uuid), public.lab_export_my_data(), public.lab_delete_my_account()
to authenticated;
grant execute on function public.lab_track(text, jsonb) to anon, authenticated;
-- administration (each checks lab_is_admin() itself)
grant execute on function
  public.lab_admin_stats(int), public.lab_admin_users(), public.lab_admin_clone_version(uuid), public.lab_admin_publish_version(uuid),
  public.lab_admin_preview_score(uuid, jsonb, jsonb), public.lab_admin_set_matching(jsonb, int, text),
  public.lab_admin_update_introduction(uuid, text, text, text), public.lab_admin_import_partners(jsonb, boolean)
to authenticated;
