-- 0014 · THE LAB — editable content
--
-- The Lab's public pages and in-app copy, as CMS pages (next/lab…) that
-- Admin → Pages edits like every other page; the homepage's "The Lab"
-- section; and a "The Lab" menu entry. Additive and idempotent.
--
-- Generated by scripts/generate-lab-content.ts from src/content/sections.en.ts.

insert into public.pages (slug, title, seo_title, seo_description, noindex) values
  ('next/lab', 'The Lab', 'The Lab · European market entry for independent brands', 'Test your brand’s readiness for a new European market, compare markets on sourced information and find compatible retail and distribution partners. By Not by Accident, Amsterdam.', false),
  ('next/lab-how', 'The Lab · How it works', 'How The Lab works · Readiness scoring and partner matching', 'The methodology behind The Lab: how expansion readiness is scored, how markets are compared and how partner matches are calculated and explained.', false),
  ('next/lab-readiness', 'The Lab · Readiness preview', 'Expansion readiness test for consumer brands · The Lab', 'Six questions, two minutes: an indicative read on how ready your brand is for a new European market. Free, and nothing you answer is stored.', false),
  ('next/lab-app', 'The Lab · App microcopy', 'The Lab', 'Your Lab workspace.', true)
on conflict (slug) do nothing;

insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'hero', 'The Lab · Market validation and matching', 'Before you enter a market, *question* it.', 'The Lab tests whether your brand is ready for a new European market, compares the markets you’re weighing, and finds partners whose records fit yours. Then it keeps track of what happens next.', null, 'Create your account', '/lab/sign-up', null, null, 0, '{"cta2Label":"Test your readiness","cta2Url":"/lab/market-readiness"}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'problem', 'The problem', 'Expansion advice arrives in pieces.', null, 'One firm sells you a market report. Another sells a database. A consultant explains the report, an agency does the outreach, and nobody joins the pieces up. The decision lands back on your desk with four invoices attached.', null, null, null, null, 1, '{}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'capabilities', 'What it does', 'Four steps, one place.', null, null, null, null, null, null, 2, '{"items":[{"title":"Validate","meta":"01","body":"About twenty questions across six areas, from positioning to returns. A readiness score you can trace back, answer by answer."},{"title":"Understand","meta":"02","body":"Up to three markets side by side. Where we hold verified information we show the source and the date it was checked. Where we don’t, we say so."},{"title":"Match","meta":"03","body":"Partners scored on category, geography, price, customer, distribution and readiness, with the reasons written out and the gaps flagged."},{"title":"Act","meta":"04","body":"Request introductions, follow their progress, and keep the conversations that matter in one short pipeline."}]}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'example', 'Example output', 'What a result looks like.', null, 'Illustrative data for a fictional jewellery brand. Not a client, not a real result.', null, null, null, null, 3, '{"overall":64,"band":"Pilot-ready potential","categories":[{"label":"Brand foundation","score":78},{"label":"Product–market fit","score":58},{"label":"Commercial readiness","score":70},{"label":"Operational readiness","score":52},{"label":"Partnership readiness","score":61},{"label":"Expansion strategy","score":66}],"match":{"name":"A concept store (fictional)","score":81,"text":"Strong category and geography alignment. Your price positioning also fits this concept store’s recorded range. Distribution requirements still need verification."}}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'method', 'How we match', 'A score you can argue with.', null, 'Every compatibility score is a weighted sum of six criteria, all visible. Missing information never counts in a partner’s favour. And a score describes fit, not interest: a high number doesn’t mean anyone is waiting for your call.', 'Read the methodology', '/lab/how-it-works', null, null, 4, '{}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'steps', 'How it works', 'From a question to a conversation.', null, null, null, null, null, null, 5, '{"items":[{"title":"Register","body":"An email address and a password. Nothing else yet."},{"title":"Describe your brand","body":"Three short steps, three to five minutes. Save and come back whenever you like."},{"title":"Take the assessment","body":"Your score, area by area, with what lifted it and what held it back."},{"title":"Compare markets","body":"Your readiness, market by market, next to what we know about each one."},{"title":"Review matches","body":"Partners ranked by fit, each with its reasons and limitations."},{"title":"Request introductions","body":"Our team reviews every request, then you follow it through here."}]}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'studio', 'Built in a studio', 'The Lab is where our studio work starts.', null, 'It grew out of the questions we ask every brand before an expansion project. Use it on your own. When you want people in the room, the studio is one conversation away.', 'Work with the studio', '/contact', null, null, 6, '{}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'faq', 'Questions', 'Before you sign up.', null, null, null, null, null, null, 7, '{"items":[{"title":"Is the readiness score a prediction?","body":"No. It summarises your own answers against a published method. A band such as “Pilot-ready potential” describes how prepared you are, not how likely you are to succeed."},{"title":"Where does the market information come from?","body":"From profiles our team maintains, each with its sources and the date it was last checked. A profile that holds basic facts only is labelled that way."},{"title":"Are the partners expecting my introduction?","body":"Not necessarily. Every partner carries a status, from research prospect to confirmed participating partner, and our team reviews each request before anyone is contacted."},{"title":"Who sees my data?","body":"You, anyone you add to your brand, and our team when running introductions. Nothing goes to a partner unless you ask for an introduction. You can export or delete everything from Settings."},{"title":"Which markets are covered?","body":"We start with the Netherlands, Germany, the United Kingdom, France, Belgium, Denmark, Sweden, Italy and Spain, and add others as we research them."}]}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'cta', null, 'Start with the questions.', null, 'An account takes a minute. The assessment takes about ten.', 'Create your account', '/lab/sign-up', null, null, 8, '{}'::jsonb
from public.pages where slug = 'next/lab'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'header', 'The Lab · Methodology', 'How the Lab *scores*.', 'Three engines, all deterministic: the same answers and the same configuration always produce the same result. No sampling, no black box.', null, null, null, null, null, 0, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'readiness', null, 'Readiness', null, 'Each question belongs to one of six areas and carries a weight. An answer earns 0 to 100 points. An area’s score is the weighted average of the questions that apply to you; questions that don’t apply, such as returns for a software company, leave the calculation instead of counting as zero. The overall score combines the areas with the weights below. Every result records the version of the questions and weights it used, so an old report never changes when the method does.', null, null, null, null, 1, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'bands', null, 'What the bands mean', null, 'Bands are product-defined readiness categories. They describe preparation, not the chance of success.', null, null, null, null, 2, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'market', null, 'Market fit', null, 'For each market we combine your overall readiness, any existing presence, language readiness, logistics capability (with a rule for crossing the EU customs border) and the partners in our database for your category. A market-fit score appears only when there is enough to go on, and markets are ranked only when the scores are at least five points apart. Every factor is labelled by where its evidence comes from: your answers, our verified profiles, our partner records or a product rule.', null, null, null, null, 3, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'matching', null, 'Matching', null, 'Clearly incompatible partners are filtered out first: excluded categories, offerings they don’t take, markets they don’t cover, a price tier two steps away. The rest are scored on six weighted criteria. A criterion we can’t evaluate earns nothing, so missing information never lifts a score, and each match lists what still needs checking.', null, null, null, null, 4, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'limits', null, 'What the numbers don’t say', null, null, null, null, null, null, 5, '{"items":[{"title":"Readiness is self-reported","body":"The score is only as accurate as the answers behind it."},{"title":"Fit is not interest","body":"A compatibility score says the recorded attributes align. It says nothing about whether a partner is looking for new brands."},{"title":"Our data has edges","body":"Market profiles and partner records are researched by our team and dated. Where we have little, we show little."}]}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'cta', null, 'See your own numbers.', null, null, 'Create your account', '/lab/sign-up', null, null, 6, '{}'::jsonb
from public.pages where slug = 'next/lab-how'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'header', 'The Lab · Readiness preview', 'How ready is your brand for a new *market*?', 'Six questions, two minutes, an indicative result. Nothing you answer here is stored.', null, null, null, null, null, 0, '{}'::jsonb
from public.pages where slug = 'next/lab-readiness'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'result', null, 'An indicative read', null, 'Based on six of the twenty or so questions in the full assessment. The full version scores six areas, explains every number, compares markets and suggests what to do next.', 'Take the full assessment', '/lab/sign-up', null, null, 1, '{}'::jsonb
from public.pages where slug = 'next/lab-readiness'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'onboarding', null, 'Tell us about your brand', null, 'Three short steps. Everything saves as you go, and you can change any of it later.', null, null, null, null, 0, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'assessment_intro', null, 'The readiness assessment', null, 'About twenty questions across six areas. Answer as things are, not as you hope they’ll be: the result is only useful if it’s true. Progress saves after every answer.', null, null, null, null, 1, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'results_note', null, null, null, 'Readiness bands are product-defined categories based on your answers. They describe how prepared you are, not how likely you are to succeed.', null, null, null, null, 2, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'markets_note', null, null, null, 'Market fit combines your answers with the facts recorded in our profiles. It describes your readiness for a market, not the size of the opportunity.', null, null, null, null, 3, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'matches_empty', null, 'We haven’t found a strong match in our current database.', null, 'That doesn’t mean one doesn’t exist. Tell us what you’re looking for and our team will research it.', 'Request research', null, null, null, 4, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'intro_note', null, null, null, 'Requests go to our team first. We check fit and context before anyone is contacted, and a compatibility score doesn’t guarantee a partner’s interest.', null, null, null, null, 5, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'opportunities_empty', null, 'No opportunities yet.', null, 'When an introduction happens it appears here. You can also add conversations you started yourself.', null, null, null, null, 6, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'reports_empty', null, 'No reports yet.', null, 'Generate one after your first assessment. It captures your readiness, markets, matches and next steps as they stand today.', null, null, null, null, 7, '{}'::jsonb
from public.pages where slug = 'next/lab-app'
on conflict (page_id, section_key) do nothing;

-- ── Homepage: The Lab ──
insert into public.page_sections (page_id, section_key, eyebrow, title, subtitle, body, cta_label, cta_url, image_media_id, video_url, sort_order, extra)
select id, 'lab', 'The Lab', 'Before you enter a market, *question* it.', null, 'A new way to understand where your brand belongs, what stands in its way, and who could help it get there.', 'Explore The Lab ↗', '/lab', null, null, 3, '{"cta2Label":"Test your readiness ↗","cta2Url":"/lab/market-readiness"}'::jsonb
from public.pages where slug = 'next/home'
on conflict (page_id, section_key) do nothing;

-- ── Menus: append "The Lab" once ──
update public.page_sections ps
set extra = jsonb_set(coalesce(ps.extra, '{}'::jsonb), '{items}', coalesce(ps.extra->'items', '[]'::jsonb) || '[{"title":"The Lab","body":"/lab"}]'::jsonb)
from public.pages p
where p.id = ps.page_id and p.slug = 'next/global' and ps.section_key in ('header_nav', 'footer_nav')
  and not exists (select 1 from jsonb_array_elements(coalesce(ps.extra->'items', '[]'::jsonb)) it where it->>'body' = '/lab');
